#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x28950ef1, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0xde16dc16, __VMLINUX_SYMBOL_STR(tboot) },
	{ 0x434693dd, __VMLINUX_SYMBOL_STR(alloc_pages_current) },
	{ 0xf37d9e, __VMLINUX_SYMBOL_STR(kvm_lapic_hv_timer_in_use) },
	{ 0x96ffcb67, __VMLINUX_SYMBOL_STR(kvm_apic_write_nodecode) },
	{ 0x34e12bb8, __VMLINUX_SYMBOL_STR(kvm_mmu_set_mask_ptes) },
	{ 0x98ab5c8d, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x3b2a63b4, __VMLINUX_SYMBOL_STR(kvm_complete_insn_gp) },
	{ 0xdbed9773, __VMLINUX_SYMBOL_STR(kvm_vcpu_write_guest) },
	{ 0x7991fd8d, __VMLINUX_SYMBOL_STR(crash_vmclear_loaded_vmcss) },
	{ 0x1ed8b599, __VMLINUX_SYMBOL_STR(__x86_indirect_thunk_r8) },
	{ 0x5ea7196f, __VMLINUX_SYMBOL_STR(kvm_cpu_get_interrupt) },
	{ 0x4c4fef19, __VMLINUX_SYMBOL_STR(kernel_stack) },
	{ 0x2548c6eb, __VMLINUX_SYMBOL_STR(kvm_mmu_sync_roots) },
	{ 0x42ab89c, __VMLINUX_SYMBOL_STR(kvm_release_page_dirty) },
	{ 0xd228cbc5, __VMLINUX_SYMBOL_STR(kvm_inject_page_fault) },
	{ 0x5885976f, __VMLINUX_SYMBOL_STR(kvm_require_dr) },
	{ 0x784213a6, __VMLINUX_SYMBOL_STR(pv_lock_ops) },
	{ 0x64020e10, __VMLINUX_SYMBOL_STR(kvm_set_shared_msr) },
	{ 0x64a34f49, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_nested_vmexit_inject) },
	{ 0x4b7dcf38, __VMLINUX_SYMBOL_STR(_raw_qspin_lock) },
	{ 0xb1baa6d, __VMLINUX_SYMBOL_STR(perf_event_release_kernel) },
	{ 0x8a540d94, __VMLINUX_SYMBOL_STR(kvm_intr_is_single_vcpu) },
	{ 0xd5f87036, __VMLINUX_SYMBOL_STR(kvm_set_msr_common) },
	{ 0x9ff982dc, __VMLINUX_SYMBOL_STR(kvm_mmu_invlpg) },
	{ 0x781acd47, __VMLINUX_SYMBOL_STR(kvm_inject_realmode_interrupt) },
	{ 0x81878f8f, __VMLINUX_SYMBOL_STR(kvm_vcpu_kick) },
	{ 0x3d4aa642, __VMLINUX_SYMBOL_STR(kvm_vcpu_init) },
	{ 0x3142b10b, __VMLINUX_SYMBOL_STR(node_data) },
	{ 0x2d101662, __VMLINUX_SYMBOL_STR(kvm_apic_set_eoi_accelerated) },
	{ 0x45449b56, __VMLINUX_SYMBOL_STR(boot_cpu_data) },
	{ 0x6696e138, __VMLINUX_SYMBOL_STR(kvm_emulate_cpuid) },
	{ 0x4c51f664, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_exit) },
	{ 0x94313d7, __VMLINUX_SYMBOL_STR(hrtimer_cancel) },
	{ 0xeafcd251, __VMLINUX_SYMBOL_STR(kvm_queue_exception_e) },
	{ 0x485cd7f6, __VMLINUX_SYMBOL_STR(kvm_rebooting) },
	{ 0x7c309fa6, __VMLINUX_SYMBOL_STR(__srcu_read_unlock) },
	{ 0xc0a3d105, __VMLINUX_SYMBOL_STR(find_next_bit) },
	{ 0xdd11f01, __VMLINUX_SYMBOL_STR(hrtimer_get_remaining) },
	{ 0xdf566a59, __VMLINUX_SYMBOL_STR(__x86_indirect_thunk_r9) },
	{ 0x2c07cedb, __VMLINUX_SYMBOL_STR(kvm_vcpu_on_spin) },
	{ 0x93346a73, __VMLINUX_SYMBOL_STR(kvm_vcpu_read_guest) },
	{ 0x50b03f5d, __VMLINUX_SYMBOL_STR(l1tf_vmx_mitigation) },
	{ 0xc87c1f84, __VMLINUX_SYMBOL_STR(ktime_get) },
	{ 0xf087137d, __VMLINUX_SYMBOL_STR(__dynamic_pr_debug) },
	{ 0xe57bd844, __VMLINUX_SYMBOL_STR(kvm_get_apic_mode) },
	{ 0xf0e8d82b, __VMLINUX_SYMBOL_STR(kvm_mmu_reset_context) },
	{ 0xc29957c3, __VMLINUX_SYMBOL_STR(__x86_indirect_thunk_rcx) },
	{ 0x7557dc76, __VMLINUX_SYMBOL_STR(kvm_mtrr_get_guest_memory_type) },
	{ 0x869a27ee, __VMLINUX_SYMBOL_STR(kvm_vcpu_reload_apic_access_page) },
	{ 0x1976aa06, __VMLINUX_SYMBOL_STR(param_ops_bool) },
	{ 0x4ed12f73, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0xf1acd059, __VMLINUX_SYMBOL_STR(mds_user_clear) },
	{ 0x46339448, __VMLINUX_SYMBOL_STR(kvm_mmu_page_fault) },
	{ 0x54efb5d6, __VMLINUX_SYMBOL_STR(cpu_number) },
	{ 0x97651e6c, __VMLINUX_SYMBOL_STR(vmemmap_base) },
	{ 0x91715312, __VMLINUX_SYMBOL_STR(sprintf) },
	{ 0xf81b8aed, __VMLINUX_SYMBOL_STR(kvm_get_dr) },
	{ 0x68199cf2, __VMLINUX_SYMBOL_STR(kvm_set_cr8) },
	{ 0x8616cca3, __VMLINUX_SYMBOL_STR(__alloc_pages_nodemask) },
	{ 0xf9c541d0, __VMLINUX_SYMBOL_STR(speculation_ctrl_update) },
	{ 0xdda018d3, __VMLINUX_SYMBOL_STR(kvm_set_cr0) },
	{ 0x343a1a8, __VMLINUX_SYMBOL_STR(__list_add) },
	{ 0x6f8bc43b, __VMLINUX_SYMBOL_STR(__x86_set_memory_region) },
	{ 0xcf5724d2, __VMLINUX_SYMBOL_STR(ssbd_userset_key) },
	{ 0xdc62e32f, __VMLINUX_SYMBOL_STR(kvm_handle_page_fault) },
	{ 0x5f6627b1, __VMLINUX_SYMBOL_STR(kvm_release_page_clean) },
	{ 0x6ac459e3, __VMLINUX_SYMBOL_STR(kvm_set_cr4) },
	{ 0x85c8e082, __VMLINUX_SYMBOL_STR(pdptrs_changed) },
	{ 0xfe7c4287, __VMLINUX_SYMBOL_STR(nr_cpu_ids) },
	{ 0xc599bc18, __VMLINUX_SYMBOL_STR(kvm_max_tsc_scaling_ratio) },
	{ 0x7e526bfa, __VMLINUX_SYMBOL_STR(__x86_indirect_thunk_r10) },
	{ 0x1cb2f5c5, __VMLINUX_SYMBOL_STR(x86_set_memory_region) },
	{ 0xfb578fc5, __VMLINUX_SYMBOL_STR(memset) },
	{ 0x96dbe382, __VMLINUX_SYMBOL_STR(kvm_mpx_supported) },
	{ 0xabd69c2, __VMLINUX_SYMBOL_STR(load_pdptrs) },
	{ 0xe125d1c6, __VMLINUX_SYMBOL_STR(kvm_get_msr) },
	{ 0xb8c7ff88, __VMLINUX_SYMBOL_STR(current_task) },
	{ 0x360b8d16, __VMLINUX_SYMBOL_STR(x86_cpu_to_apicid) },
	{ 0x308e30fb, __VMLINUX_SYMBOL_STR(kvm_get_linear_rip) },
	{ 0xd0459e67, __VMLINUX_SYMBOL_STR(kvm_has_tsc_control) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x709cd8cb, __VMLINUX_SYMBOL_STR(kvm_spurious_fault) },
	{ 0x449ad0a7, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0x3b5dd35e, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_msr) },
	{ 0xf844e95f, __VMLINUX_SYMBOL_STR(spec_ctrl_pcp) },
	{ 0x4c9d28b0, __VMLINUX_SYMBOL_STR(phys_base) },
	{ 0xf8404aba, __VMLINUX_SYMBOL_STR(kvm_emulate_hypercall) },
	{ 0xa523566a, __VMLINUX_SYMBOL_STR(kvm_set_msi_irq) },
	{ 0x4d77e88b, __VMLINUX_SYMBOL_STR(kvm_set_dr) },
	{ 0xe974f684, __VMLINUX_SYMBOL_STR(kvm_vcpu_cache) },
	{ 0xa1c76e0a, __VMLINUX_SYMBOL_STR(_cond_resched) },
	{ 0x8941886e, __VMLINUX_SYMBOL_STR(vcpu_load) },
	{ 0x7a872988, __VMLINUX_SYMBOL_STR(kvm_x86_ops) },
	{ 0x6636c3c9, __VMLINUX_SYMBOL_STR(irq_set_vcpu_affinity) },
	{ 0x5e8f0019, __VMLINUX_SYMBOL_STR(kvm_get_cr8) },
	{ 0x19ee3d71, __VMLINUX_SYMBOL_STR(kmem_cache_free) },
	{ 0xdd55693f, __VMLINUX_SYMBOL_STR(kvm_lapic_switch_to_sw_timer) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0x3b91db5b, __VMLINUX_SYMBOL_STR(intel_pt_handle_vmx) },
	{ 0x9abdea30, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x696d7e0b, __VMLINUX_SYMBOL_STR(l1tf_mitigation) },
	{ 0xabcb2807, __VMLINUX_SYMBOL_STR(kvm_set_cr3) },
	{ 0x521445b, __VMLINUX_SYMBOL_STR(list_del) },
	{ 0x6baf060, __VMLINUX_SYMBOL_STR(kvm_emulate_wbinvd) },
	{ 0xf4be47, __VMLINUX_SYMBOL_STR(sched_smt_present) },
	{ 0x4cb8bb31, __VMLINUX_SYMBOL_STR(kvm_init_mmu) },
	{ 0xc2cdbf1, __VMLINUX_SYMBOL_STR(synchronize_sched) },
	{ 0x1b01eeaa, __VMLINUX_SYMBOL_STR(kvm_apic_update_irr) },
	{ 0xd96a2de6, __VMLINUX_SYMBOL_STR(__srcu_read_lock) },
	{ 0xb6a68816, __VMLINUX_SYMBOL_STR(find_last_bit) },
	{ 0x29f52963, __VMLINUX_SYMBOL_STR(kvm_before_handle_nmi) },
	{ 0x8b850a78, __VMLINUX_SYMBOL_STR(cpu_bit_bitmap) },
	{ 0xeeb4bb40, __VMLINUX_SYMBOL_STR(kvm_apic_update_ppr) },
	{ 0x1e1fdb0a, __VMLINUX_SYMBOL_STR(__kvm_apic_update_irr) },
	{ 0xe3c5dd4, __VMLINUX_SYMBOL_STR(kvm_cpu_has_interrupt) },
	{ 0x53a2a3f7, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_inj_virq) },
	{ 0x136cef65, __VMLINUX_SYMBOL_STR(kvm_read_l1_tsc) },
	{ 0xb0404b01, __VMLINUX_SYMBOL_STR(kvm_mmu_slot_set_dirty) },
	{ 0x2e2df7f4, __VMLINUX_SYMBOL_STR(irq_remapping_cap) },
	{ 0x7f9980ba, __VMLINUX_SYMBOL_STR(kvm_mmu_free_roots) },
	{ 0x9ee59155, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_page_fault) },
	{ 0xf11543ff, __VMLINUX_SYMBOL_STR(find_first_zero_bit) },
	{ 0x8edde706, __VMLINUX_SYMBOL_STR(retp_enabled_key) },
	{ 0x34d01a87, __VMLINUX_SYMBOL_STR(kvm_mce_cap_supported) },
	{ 0xf2f286c4, __VMLINUX_SYMBOL_STR(kvm_tsc_scaling_ratio_frac_bits) },
	{ 0x7cd8d75e, __VMLINUX_SYMBOL_STR(page_offset_base) },
	{ 0x5d4966cf, __VMLINUX_SYMBOL_STR(kvm_mmu_slot_leaf_clear_dirty) },
	{ 0xa70c6a59, __VMLINUX_SYMBOL_STR(kvm_valid_efer) },
	{ 0xd11b7a3e, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0x78764f4e, __VMLINUX_SYMBOL_STR(pv_irq_ops) },
	{ 0xa281370e, __VMLINUX_SYMBOL_STR(__free_pages) },
	{ 0xc287d96a, __VMLINUX_SYMBOL_STR(kvm_set_posted_intr_wakeup_handler) },
	{ 0x8036176f, __VMLINUX_SYMBOL_STR(kvm_write_guest_page) },
	{ 0xb601be4c, __VMLINUX_SYMBOL_STR(__x86_indirect_thunk_rdx) },
	{ 0x618911fc, __VMLINUX_SYMBOL_STR(numa_node) },
	{ 0xe96c795, __VMLINUX_SYMBOL_STR(x86_spec_ctrl_base) },
	{ 0x12fa1081, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_pi_irte_update) },
	{ 0x8ecfc437, __VMLINUX_SYMBOL_STR(kvm_vcpu_is_reset_bsp) },
	{ 0xcef3fec5, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_write_tsc_offset) },
	{ 0x93fca811, __VMLINUX_SYMBOL_STR(__get_free_pages) },
	{ 0x54145efa, __VMLINUX_SYMBOL_STR(kvm_after_handle_nmi) },
	{ 0x3913c84e, __VMLINUX_SYMBOL_STR(kvm_lapic_switch_to_hv_timer) },
	{ 0xf0fdf6cb, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0x615210c3, __VMLINUX_SYMBOL_STR(kvm_queue_exception) },
	{ 0xc311ec22, __VMLINUX_SYMBOL_STR(cpu_possible_mask) },
	{ 0x1000e51, __VMLINUX_SYMBOL_STR(schedule) },
	{ 0x155f4108, __VMLINUX_SYMBOL_STR(___ratelimit) },
	{ 0x77b02cb8, __VMLINUX_SYMBOL_STR(kvm_lapic_set_eoi) },
	{ 0x775a6ef5, __VMLINUX_SYMBOL_STR(kvm_read_and_reset_pf_reason) },
	{ 0x1c1a9cf4, __VMLINUX_SYMBOL_STR(kvm_lmsw) },
	{ 0x6b2dc060, __VMLINUX_SYMBOL_STR(dump_stack) },
	{ 0x6e8bf789, __VMLINUX_SYMBOL_STR(hrtimer_start) },
	{ 0xc822372c, __VMLINUX_SYMBOL_STR(kvm_requeue_exception_e) },
	{ 0x2d65f8c7, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_pml_full) },
	{ 0xc82e16bd, __VMLINUX_SYMBOL_STR(kvm_init_shadow_ept_mmu) },
	{ 0x2ea2c95c, __VMLINUX_SYMBOL_STR(__x86_indirect_thunk_rax) },
	{ 0xbfdcb43a, __VMLINUX_SYMBOL_STR(__x86_indirect_thunk_r11) },
	{ 0x910538ff, __VMLINUX_SYMBOL_STR(pv_cpu_ops) },
	{ 0xaf1530a8, __VMLINUX_SYMBOL_STR(kvm_require_cpl) },
	{ 0xaaf935, __VMLINUX_SYMBOL_STR(kvm_disable_tdp) },
	{ 0x65428277, __VMLINUX_SYMBOL_STR(kvm_mmu_clear_dirty_pt_masked) },
	{ 0x9144a70, __VMLINUX_SYMBOL_STR(kvm_mmu_set_mmio_spte_mask) },
	{ 0xecf823a, __VMLINUX_SYMBOL_STR(static_key_slow_dec) },
	{ 0x8c801f6b, __VMLINUX_SYMBOL_STR(kvm_io_bus_write) },
	{ 0xaa79cab5, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_cr) },
	{ 0x1f7af249, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_ple_window) },
	{ 0xd3640835, __VMLINUX_SYMBOL_STR(x86_emulate_instruction) },
	{ 0x56303d10, __VMLINUX_SYMBOL_STR(kvm_vcpu_gfn_to_page) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
	{ 0xccdaabd2, __VMLINUX_SYMBOL_STR(kvm_read_guest_virt) },
	{ 0x8ce4f3ab, __VMLINUX_SYMBOL_STR(kvm_enable_tdp) },
	{ 0x31b72231, __VMLINUX_SYMBOL_STR(kvm_task_switch) },
	{ 0x55c4fe9d, __VMLINUX_SYMBOL_STR(kvm_find_cpuid_entry) },
	{ 0x41ec4c1a, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x9ee4dd7d, __VMLINUX_SYMBOL_STR(kvm_write_guest_virt_system) },
	{ 0x5df7a209, __VMLINUX_SYMBOL_STR(perf_event_read_value) },
	{ 0xd94cc09, __VMLINUX_SYMBOL_STR(__per_cpu_offset) },
	{ 0x58f57f0e, __VMLINUX_SYMBOL_STR(kvm_mtrr_valid) },
	{ 0x350828cd, __VMLINUX_SYMBOL_STR(reprogram_gp_counter) },
	{ 0x12fd5ff1, __VMLINUX_SYMBOL_STR(kvm_set_xcr) },
	{ 0x9a216313, __VMLINUX_SYMBOL_STR(kvm_define_shared_msr) },
	{ 0x2cd4f5f0, __VMLINUX_SYMBOL_STR(kvm_lapic_find_highest_irr) },
	{ 0x4302d0eb, __VMLINUX_SYMBOL_STR(free_pages) },
	{ 0x1e047854, __VMLINUX_SYMBOL_STR(warn_slowpath_fmt) },
	{ 0x2c0dbd77, __VMLINUX_SYMBOL_STR(kvm_set_apic_base) },
	{ 0x82b05d14, __VMLINUX_SYMBOL_STR(kvm_emulate_halt) },
	{ 0x31fac6a6, __VMLINUX_SYMBOL_STR(kvm_arch_has_noncoherent_dma) },
	{ 0xb8f2bfda, __VMLINUX_SYMBOL_STR(kvm_vcpu_uninit) },
	{ 0x6d27ef64, __VMLINUX_SYMBOL_STR(__bitmap_empty) },
	{ 0xf297cd96, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_fast_mmio) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0xd5c954, __VMLINUX_SYMBOL_STR(kvm_mmu_slot_largepage_remove_write_access) },
	{ 0x73a0349b, __VMLINUX_SYMBOL_STR(kvm_get_msr_common) },
	{ 0x72392fe6, __VMLINUX_SYMBOL_STR(pv_mmu_ops) },
	{ 0x27956a4d, __VMLINUX_SYMBOL_STR(reprogram_fixed_counter) },
	{ 0x25a97010, __VMLINUX_SYMBOL_STR(hrtimer_init) },
	{ 0x3f8f9119, __VMLINUX_SYMBOL_STR(kvm_no_apic_vcpu) },
	{ 0x6194ffea, __VMLINUX_SYMBOL_STR(do_machine_check) },
	{ 0xdae34e75, __VMLINUX_SYMBOL_STR(kvm_vcpu_write_guest_page) },
	{ 0x7628f3c7, __VMLINUX_SYMBOL_STR(this_cpu_off) },
	{ 0x334c1f75, __VMLINUX_SYMBOL_STR(put_page) },
	{ 0xb352177e, __VMLINUX_SYMBOL_STR(find_first_bit) },
	{ 0xbdedfff, __VMLINUX_SYMBOL_STR(gfn_to_page) },
	{ 0xd3eaa47, __VMLINUX_SYMBOL_STR(static_key_enabled) },
	{ 0x12457dca, __VMLINUX_SYMBOL_STR(x86_spec_ctrl_mask) },
	{ 0x80e5c75c, __VMLINUX_SYMBOL_STR(kvm_lapic_expired_hv_timer) },
	{ 0x5c944fd4, __VMLINUX_SYMBOL_STR(kvm_fast_pio_out) },
	{ 0x222e7ce2, __VMLINUX_SYMBOL_STR(sysfs_streq) },
	{ 0x317f9e6b, __VMLINUX_SYMBOL_STR(kvm_enable_efer_bits) },
	{ 0x13fd14df, __VMLINUX_SYMBOL_STR(ibrs_present_key) },
	{ 0x512101d1, __VMLINUX_SYMBOL_STR(apic) },
	{ 0x7f2c1163, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_nested_vmexit) },
	{ 0xafaffb, __VMLINUX_SYMBOL_STR(kvm_default_tsc_scaling_ratio) },
	{ 0x1267a56a, __VMLINUX_SYMBOL_STR(kvm_set_msr) },
	{ 0x368f1fea, __VMLINUX_SYMBOL_STR(static_key_slow_inc) },
	{ 0x321fddc7, __VMLINUX_SYMBOL_STR(kvm_init) },
	{ 0x27046576, __VMLINUX_SYMBOL_STR(kvm_exit) },
	{ 0xff073966, __VMLINUX_SYMBOL_STR(reprogram_counter) },
	{ 0x6d044c26, __VMLINUX_SYMBOL_STR(param_ops_uint) },
	{ 0x48682db9, __VMLINUX_SYMBOL_STR(perf_guest_get_msrs) },
	{ 0x20de5193, __VMLINUX_SYMBOL_STR(kvm_disable_largepages) },
	{ 0xcd2c0ec9, __VMLINUX_SYMBOL_STR(kvm_requeue_exception) },
	{ 0x3a005c22, __VMLINUX_SYMBOL_STR(kvm_clear_guest_page) },
	{ 0x897e168b, __VMLINUX_SYMBOL_STR(kvm_vcpu_halt) },
	{ 0x6228c21f, __VMLINUX_SYMBOL_STR(smp_call_function_single) },
	{ 0xd88f013f, __VMLINUX_SYMBOL_STR(kvm_vcpu_mark_page_dirty) },
	{ 0x2fe3eafb, __VMLINUX_SYMBOL_STR(kvm_rdpmc) },
	{ 0xd49ee82b, __VMLINUX_SYMBOL_STR(kvm_arch_has_assigned_device) },
	{ 0x69c3c5d1, __VMLINUX_SYMBOL_STR(vcpu_put) },
	{ 0xdda1ddd5, __VMLINUX_SYMBOL_STR(kvm_mmu_new_cr3) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=kvm";

MODULE_ALIAS("x86cpu:vendor:*:family:*:model:*:feature:*0085*");

MODULE_INFO(srcversion, "662FB0DDC202C6E16AFB14B");
MODULE_INFO(rhelversion, "7.7");
#ifdef RETPOLINE
	MODULE_INFO(retpoline, "Y");
#endif
#ifdef CONFIG_MPROFILE_KERNEL
	MODULE_INFO(mprofile, "Y");
#endif
