#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x28950ef1, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x2c49f4d1, __VMLINUX_SYMBOL_STR(rdma_resolve_ip) },
	{ 0x3588d8ba, __VMLINUX_SYMBOL_STR(_raw_qspin_lock_irq) },
	{ 0x66f87150, __VMLINUX_SYMBOL_STR(register_netdevice_notifier_rh) },
	{ 0x98ab5c8d, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x5825715a, __VMLINUX_SYMBOL_STR(rdma_copy_src_l2_addr) },
	{ 0x65e75cb6, __VMLINUX_SYMBOL_STR(__list_del_entry) },
	{ 0xd2b09ce5, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0xf1a3749b, __VMLINUX_SYMBOL_STR(ib_send_cm_rej) },
	{ 0xea914884, __VMLINUX_SYMBOL_STR(iw_cm_listen) },
	{ 0x24e23b71, __VMLINUX_SYMBOL_STR(ib_attach_mcast) },
	{ 0x784213a6, __VMLINUX_SYMBOL_STR(pv_lock_ops) },
	{ 0xa60dd38b, __VMLINUX_SYMBOL_STR(rdma_nl_register) },
	{ 0x4b7dcf38, __VMLINUX_SYMBOL_STR(_raw_qspin_lock) },
	{ 0x48316485, __VMLINUX_SYMBOL_STR(__fib_lookup) },
	{ 0x43a53735, __VMLINUX_SYMBOL_STR(__alloc_workqueue_key) },
	{ 0x79aa04a2, __VMLINUX_SYMBOL_STR(get_random_bytes) },
	{ 0xfd72385b, __VMLINUX_SYMBOL_STR(roce_gid_type_mask_support) },
	{ 0xecbcd7f6, __VMLINUX_SYMBOL_STR(ib_sa_join_multicast) },
	{ 0xc55c4b8a, __VMLINUX_SYMBOL_STR(ib_send_cm_req) },
	{ 0x285afd68, __VMLINUX_SYMBOL_STR(ib_send_cm_dreq) },
	{ 0xc7a4fbed, __VMLINUX_SYMBOL_STR(rtnl_lock) },
	{ 0x4c22db20, __VMLINUX_SYMBOL_STR(ib_send_cm_rtu) },
	{ 0x9d633750, __VMLINUX_SYMBOL_STR(dst_release) },
	{ 0xc2fc84b7, __VMLINUX_SYMBOL_STR(iw_cm_init_qp_attr) },
	{ 0x139bf3ad, __VMLINUX_SYMBOL_STR(ib_destroy_qp) },
	{ 0x69824a14, __VMLINUX_SYMBOL_STR(ibcm_reject_msg) },
	{ 0x14de1f76, __VMLINUX_SYMBOL_STR(iw_cm_reject) },
	{ 0xf087137d, __VMLINUX_SYMBOL_STR(__dynamic_pr_debug) },
	{ 0x448eac3e, __VMLINUX_SYMBOL_STR(kmemdup) },
	{ 0x4ed12f73, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0xb4e088aa, __VMLINUX_SYMBOL_STR(iw_cm_accept) },
	{ 0x91715312, __VMLINUX_SYMBOL_STR(sprintf) },
	{ 0xbe52ee31, __VMLINUX_SYMBOL_STR(__put_net) },
	{ 0x343a1a8, __VMLINUX_SYMBOL_STR(__list_add) },
	{ 0xb107c467, __VMLINUX_SYMBOL_STR(ib_modify_qp) },
	{ 0x65f8c888, __VMLINUX_SYMBOL_STR(rdma_restrack_del) },
	{ 0xe2d5255a, __VMLINUX_SYMBOL_STR(strcmp) },
	{ 0x188a9430, __VMLINUX_SYMBOL_STR(ib_send_cm_mra) },
	{ 0xda8bb6d3, __VMLINUX_SYMBOL_STR(ib_get_cached_port_state) },
	{ 0xf4b9b41b, __VMLINUX_SYMBOL_STR(ib_sa_free_multicast) },
	{ 0x85bc493e, __VMLINUX_SYMBOL_STR(ib_get_net_dev_by_params) },
	{ 0xf432dd3d, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0x3a109be0, __VMLINUX_SYMBOL_STR(ib_create_qp) },
	{ 0x6d0aba34, __VMLINUX_SYMBOL_STR(wait_for_completion) },
	{ 0xf7612736, __VMLINUX_SYMBOL_STR(ib_send_cm_drep) },
	{ 0xe0caf319, __VMLINUX_SYMBOL_STR(ib_cm_init_qp_attr) },
	{ 0xf6c6637d, __VMLINUX_SYMBOL_STR(unregister_pernet_subsys) },
	{ 0x45c92723, __VMLINUX_SYMBOL_STR(idr_destroy) },
	{ 0xf3df871f, __VMLINUX_SYMBOL_STR(iwcm_reject_msg) },
	{ 0x5a5a94a6, __VMLINUX_SYMBOL_STR(kstrtou8) },
	{ 0x8f64aa4, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irqrestore) },
	{ 0xc49d3c41, __VMLINUX_SYMBOL_STR(__ethtool_get_link_ksettings) },
	{ 0x9a025cd5, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0xcfd55ae7, __VMLINUX_SYMBOL_STR(iw_cm_disconnect) },
	{ 0x9ed42be6, __VMLINUX_SYMBOL_STR(ibnl_put_attr) },
	{ 0x449ad0a7, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0xe7b00dfb, __VMLINUX_SYMBOL_STR(__x86_indirect_thunk_r13) },
	{ 0x90e807c7, __VMLINUX_SYMBOL_STR(ib_cache_gid_parse_type_str) },
	{ 0x2c45b349, __VMLINUX_SYMBOL_STR(ib_send_cm_rep) },
	{ 0x5792f848, __VMLINUX_SYMBOL_STR(strlcpy) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0x9abdea30, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x8c03d20c, __VMLINUX_SYMBOL_STR(destroy_workqueue) },
	{ 0x521445b, __VMLINUX_SYMBOL_STR(list_del) },
	{ 0x76e7d329, __VMLINUX_SYMBOL_STR(iw_destroy_cm_id) },
	{ 0xb4d5d033, __VMLINUX_SYMBOL_STR(dev_get_by_index) },
	{ 0x7e5bef8b, __VMLINUX_SYMBOL_STR(config_group_init_type_name) },
	{ 0xa023d66f, __VMLINUX_SYMBOL_STR(rdma_put_gid_attr) },
	{ 0xa735db59, __VMLINUX_SYMBOL_STR(prandom_u32) },
	{ 0x4fd5cfb9, __VMLINUX_SYMBOL_STR(idr_alloc) },
	{ 0xfe750b57, __VMLINUX_SYMBOL_STR(configfs_register_subsystem) },
	{ 0x525828b4, __VMLINUX_SYMBOL_STR(ib_get_cached_pkey) },
	{ 0xdcca836e, __VMLINUX_SYMBOL_STR(init_net) },
	{ 0x3e1fe0f4, __VMLINUX_SYMBOL_STR(ib_set_client_data) },
	{ 0xef0516fe, __VMLINUX_SYMBOL_STR(rdma_destroy_ah_attr) },
	{ 0x3e767ef2, __VMLINUX_SYMBOL_STR(rdma_restrack_set_task) },
	{ 0x6e619aed, __VMLINUX_SYMBOL_STR(ib_init_ah_from_mcmember) },
	{ 0x75a729a0, __VMLINUX_SYMBOL_STR(rdma_nl_unregister) },
	{ 0x2fd0e42f, __VMLINUX_SYMBOL_STR(ib_sa_unregister_client) },
	{ 0x86971169, __VMLINUX_SYMBOL_STR(vlan_dev_real_dev) },
	{ 0x17401634, __VMLINUX_SYMBOL_STR(ib_create_cm_id) },
	{ 0xbd8bce19, __VMLINUX_SYMBOL_STR(__task_pid_nr_ns) },
	{ 0xe0c56318, __VMLINUX_SYMBOL_STR(ib_sa_path_rec_get) },
	{ 0xcaef1b77, __VMLINUX_SYMBOL_STR(idr_remove) },
	{ 0x400919de, __VMLINUX_SYMBOL_STR(ib_register_client) },
	{ 0xda0d50ec, __VMLINUX_SYMBOL_STR(ib_sa_cancel_query) },
	{ 0xc6cbbc89, __VMLINUX_SYMBOL_STR(capable) },
	{ 0x78764f4e, __VMLINUX_SYMBOL_STR(pv_irq_ops) },
	{ 0xb601be4c, __VMLINUX_SYMBOL_STR(__x86_indirect_thunk_rdx) },
	{ 0x6f36c782, __VMLINUX_SYMBOL_STR(idr_find_slowpath) },
	{ 0x85a0503a, __VMLINUX_SYMBOL_STR(ib_sa_get_mcmember_rec) },
	{ 0xa916b694, __VMLINUX_SYMBOL_STR(strnlen) },
	{ 0x7ce0eb43, __VMLINUX_SYMBOL_STR(ib_detach_mcast) },
	{ 0x8a25fc35, __VMLINUX_SYMBOL_STR(ib_cm_notify) },
	{ 0xfce089f4, __VMLINUX_SYMBOL_STR(rdma_addr_cancel) },
	{ 0xf0fdf6cb, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0x680073a0, __VMLINUX_SYMBOL_STR(rdma_restrack_add) },
	{ 0xfb0194a3, __VMLINUX_SYMBOL_STR(iw_cm_connect) },
	{ 0x155f4108, __VMLINUX_SYMBOL_STR(___ratelimit) },
	{ 0x1fbd16da, __VMLINUX_SYMBOL_STR(ip_tos2prio) },
	{ 0x19428dd6, __VMLINUX_SYMBOL_STR(unregister_netdevice_notifier_rh) },
	{ 0x2ea2c95c, __VMLINUX_SYMBOL_STR(__x86_indirect_thunk_rax) },
	{ 0x8537993f, __VMLINUX_SYMBOL_STR(ib_find_cached_pkey) },
	{ 0x8c053a79, __VMLINUX_SYMBOL_STR(ip_mc_inc_group) },
	{ 0x7679e2bb, __VMLINUX_SYMBOL_STR(register_pernet_subsys) },
	{ 0x7177984c, __VMLINUX_SYMBOL_STR(configfs_unregister_subsystem) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
	{ 0x5611cdea, __VMLINUX_SYMBOL_STR(rdma_node_get_transport) },
	{ 0x41ec4c1a, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x7b89cc2e, __VMLINUX_SYMBOL_STR(ib_destroy_cm_id) },
	{ 0x9327f5ce, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irqsave) },
	{ 0x86cef180, __VMLINUX_SYMBOL_STR(rdma_addr_size) },
	{ 0x3f27fb9d, __VMLINUX_SYMBOL_STR(fib_table_lookup) },
	{ 0x5061e0ef, __VMLINUX_SYMBOL_STR(rdma_translate_ip) },
	{ 0x7b58e478, __VMLINUX_SYMBOL_STR(rt6_lookup) },
	{ 0x86c08cc2, __VMLINUX_SYMBOL_STR(rdma_query_gid) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x69acdf38, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0xc1955a3f, __VMLINUX_SYMBOL_STR(ib_sa_register_client) },
	{ 0x2afd9e8e, __VMLINUX_SYMBOL_STR(ib_sa_sendonly_fullmem_support) },
	{ 0xb352177e, __VMLINUX_SYMBOL_STR(find_first_bit) },
	{ 0x41f54a0c, __VMLINUX_SYMBOL_STR(dev_warn) },
	{ 0xed57a326, __VMLINUX_SYMBOL_STR(ib_cm_insert_listen) },
	{ 0x2e0d2f7f, __VMLINUX_SYMBOL_STR(queue_work_on) },
	{ 0x4b06d2e7, __VMLINUX_SYMBOL_STR(complete) },
	{ 0x28318305, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0xdda9b6b9, __VMLINUX_SYMBOL_STR(rdma_find_gid_by_port) },
	{ 0xb1b42470, __VMLINUX_SYMBOL_STR(idr_init) },
	{ 0xb8f73e72, __VMLINUX_SYMBOL_STR(ib_init_ah_attr_from_path) },
	{ 0x62931304, __VMLINUX_SYMBOL_STR(ibnl_put_msg) },
	{ 0x53a328ea, __VMLINUX_SYMBOL_STR(ip_mc_dec_group) },
	{ 0x5128c858, __VMLINUX_SYMBOL_STR(config_group_init) },
	{ 0xa2122ed7, __VMLINUX_SYMBOL_STR(ib_send_cm_sidr_rep) },
	{ 0x9cc0cc0c, __VMLINUX_SYMBOL_STR(ib_unregister_client) },
	{ 0xd542439, __VMLINUX_SYMBOL_STR(__ipv6_addr_type) },
	{ 0x3c27b2f8, __VMLINUX_SYMBOL_STR(inet_get_local_port_range) },
	{ 0x1634eb9d, __VMLINUX_SYMBOL_STR(iw_create_cm_id) },
	{ 0x6e720ff2, __VMLINUX_SYMBOL_STR(rtnl_unlock) },
	{ 0x2a91bb33, __VMLINUX_SYMBOL_STR(ib_cache_gid_type_str) },
	{ 0xc3ce2718, __VMLINUX_SYMBOL_STR(ib_send_cm_sidr_req) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=ib_core,ib_cm,iw_cm";


MODULE_INFO(srcversion, "0442E10184EA4CAB7192D10");
MODULE_INFO(rhelversion, "7.7");
#ifdef RETPOLINE
	MODULE_INFO(retpoline, "Y");
#endif
#ifdef CONFIG_MPROFILE_KERNEL
	MODULE_INFO(mprofile, "Y");
#endif
