#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x28950ef1, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x2d3385d3, __VMLINUX_SYMBOL_STR(system_wq) },
	{ 0x98ab5c8d, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0xd2b09ce5, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0xf9a482f9, __VMLINUX_SYMBOL_STR(msleep) },
	{ 0xba954a0e, __VMLINUX_SYMBOL_STR(__pm_runtime_idle) },
	{ 0xd777bd2d, __VMLINUX_SYMBOL_STR(sst_module_new) },
	{ 0x1ed8b599, __VMLINUX_SYMBOL_STR(__x86_indirect_thunk_r8) },
	{ 0x4c4fef19, __VMLINUX_SYMBOL_STR(kernel_stack) },
	{ 0xd16b0c74, __VMLINUX_SYMBOL_STR(sst_dsp_reset) },
	{ 0x49dc84dd, __VMLINUX_SYMBOL_STR(__pm_runtime_disable) },
	{ 0x784213a6, __VMLINUX_SYMBOL_STR(pv_lock_ops) },
	{ 0x602ec3d7, __VMLINUX_SYMBOL_STR(sst_mem_block_register) },
	{ 0xd817101e, __VMLINUX_SYMBOL_STR(sst_dsp_wake) },
	{ 0x4b7dcf38, __VMLINUX_SYMBOL_STR(_raw_qspin_lock) },
	{ 0x4a045773, __VMLINUX_SYMBOL_STR(sst_shim32_write) },
	{ 0x3906ef29, __VMLINUX_SYMBOL_STR(__pm_runtime_use_autosuspend) },
	{ 0x754d539c, __VMLINUX_SYMBOL_STR(strlen) },
	{ 0xdc22e6a0, __VMLINUX_SYMBOL_STR(sst_dsp_get_offset) },
	{ 0x5e7f4920, __VMLINUX_SYMBOL_STR(snd_pcm_format_set_silence) },
	{ 0xc483a55a, __VMLINUX_SYMBOL_STR(dev_set_drvdata) },
	{ 0xa0d3db3b, __VMLINUX_SYMBOL_STR(__pm_runtime_suspend) },
	{ 0x3a78144a, __VMLINUX_SYMBOL_STR(snd_pcm_period_elapsed) },
	{ 0x6999e161, __VMLINUX_SYMBOL_STR(sst_dsp_shim_write) },
	{ 0xc8b57c27, __VMLINUX_SYMBOL_STR(autoremove_wake_function) },
	{ 0x16fb15f9, __VMLINUX_SYMBOL_STR(snd_dma_alloc_pages) },
	{ 0x7ae5ad74, __VMLINUX_SYMBOL_STR(sme_active) },
	{ 0x59d5a7f7, __VMLINUX_SYMBOL_STR(dma_set_mask) },
	{ 0x7b4e706f, __VMLINUX_SYMBOL_STR(sst_module_get_from_id) },
	{ 0xe4d75ac0, __VMLINUX_SYMBOL_STR(sst_dsp_outbox_read) },
	{ 0xcf074e2, __VMLINUX_SYMBOL_STR(snd_soc_set_runtime_hwparams) },
	{ 0x696f3eab, __VMLINUX_SYMBOL_STR(sst_fw_new) },
	{ 0x1ec5faef, __VMLINUX_SYMBOL_STR(sst_dsp_dma_get_channel) },
	{ 0x45fa82a1, __VMLINUX_SYMBOL_STR(sst_dsp_dma_put_channel) },
	{ 0x88bfa7e, __VMLINUX_SYMBOL_STR(cancel_work_sync) },
	{ 0xc29957c3, __VMLINUX_SYMBOL_STR(__x86_indirect_thunk_rcx) },
	{ 0xeae3dfd6, __VMLINUX_SYMBOL_STR(__const_udelay) },
	{ 0x76d756b9, __VMLINUX_SYMBOL_STR(sst_memcpy_toio_32) },
	{ 0x47d4fd87, __VMLINUX_SYMBOL_STR(sst_dsp_inbox_read) },
	{ 0x9621849f, __VMLINUX_SYMBOL_STR(ring_buffer_event_data) },
	{ 0x4ed12f73, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x85df9b6c, __VMLINUX_SYMBOL_STR(strsep) },
	{ 0x7baababe, __VMLINUX_SYMBOL_STR(__pm_runtime_resume) },
	{ 0x33c056fc, __VMLINUX_SYMBOL_STR(sst_dsp_outbox_write) },
	{ 0x912b5f0b, __VMLINUX_SYMBOL_STR(filter_current_check_discard) },
	{ 0x9e7f4a92, __VMLINUX_SYMBOL_STR(sst_dsp_shim_update_bits) },
	{ 0x5b0240c6, __VMLINUX_SYMBOL_STR(__platform_driver_register) },
	{ 0x7d11c268, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0x343a1a8, __VMLINUX_SYMBOL_STR(__list_add) },
	{ 0xab5cf1e0, __VMLINUX_SYMBOL_STR(sst_dsp_dma_copyfrom) },
	{ 0x2e1da10a, __VMLINUX_SYMBOL_STR(snd_pcm_suspend_all) },
	{ 0xcaf51fe4, __VMLINUX_SYMBOL_STR(sst_ipc_tx_msg_reply_complete) },
	{ 0xbc2c4be8, __VMLINUX_SYMBOL_STR(sst_ipc_reply_find_msg) },
	{ 0xf432dd3d, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0x36e194d7, __VMLINUX_SYMBOL_STR(sst_dsp_mailbox_init) },
	{ 0xc133073d, __VMLINUX_SYMBOL_STR(sst_module_runtime_restore) },
	{ 0x951f1fb2, __VMLINUX_SYMBOL_STR(sst_dsp_stall) },
	{ 0x712f6943, __VMLINUX_SYMBOL_STR(sst_module_runtime_new) },
	{ 0x1b5e8b82, __VMLINUX_SYMBOL_STR(sst_shim32_read) },
	{ 0xa0b5b192, __VMLINUX_SYMBOL_STR(trace_event_buffer_lock_reserve) },
	{ 0xe2253bd7, __VMLINUX_SYMBOL_STR(trace_define_field) },
	{ 0xa709c2ff, __VMLINUX_SYMBOL_STR(snd_soc_poweroff) },
	{ 0xdecb3369, __VMLINUX_SYMBOL_STR(snd_pcm_sgbuf_ops_page) },
	{ 0xfb578fc5, __VMLINUX_SYMBOL_STR(memset) },
	{ 0x51b04ed4, __VMLINUX_SYMBOL_STR(sst_dsp_dma_copyto) },
	{ 0x1d4519c, __VMLINUX_SYMBOL_STR(dev_err) },
	{ 0x8f64aa4, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irqrestore) },
	{ 0xb8c7ff88, __VMLINUX_SYMBOL_STR(current_task) },
	{ 0x9a025cd5, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0xf934eaba, __VMLINUX_SYMBOL_STR(sst_dsp_sleep) },
	{ 0x3c4ff116, __VMLINUX_SYMBOL_STR(sst_ipc_init) },
	{ 0x4d1406d7, __VMLINUX_SYMBOL_STR(sst_dsp_shim_update_bits_unlocked) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0x9abdea30, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x521445b, __VMLINUX_SYMBOL_STR(list_del) },
	{ 0x4e6daf04, __VMLINUX_SYMBOL_STR(snd_pcm_lib_free_pages) },
	{ 0x8845b1f5, __VMLINUX_SYMBOL_STR(sst_ipc_fini) },
	{ 0x507622fb, __VMLINUX_SYMBOL_STR(sst_mem_block_unregister_all) },
	{ 0xbd262c4e, __VMLINUX_SYMBOL_STR(sst_dsp_ipc_msg_tx) },
	{ 0x57d13b7c, __VMLINUX_SYMBOL_STR(snd_pcm_lib_ioctl) },
	{ 0xbcec5387, __VMLINUX_SYMBOL_STR(sst_shim32_read64) },
	{ 0x3de2640, __VMLINUX_SYMBOL_STR(perf_trace_run_bpf_submit) },
	{ 0x2cb58043, __VMLINUX_SYMBOL_STR(sst_dsp_shim_read_unlocked) },
	{ 0x596f5598, __VMLINUX_SYMBOL_STR(snd_ctl_boolean_mono_info) },
	{ 0x6728e776, __VMLINUX_SYMBOL_STR(snd_pcm_lib_malloc_pages) },
	{ 0xfb2cdc19, __VMLINUX_SYMBOL_STR(snd_soc_info_volsw) },
	{ 0xd9a2c94c, __VMLINUX_SYMBOL_STR(sst_shim32_write64) },
	{ 0xa587ed11, __VMLINUX_SYMBOL_STR(arch_dma_alloc_attrs) },
	{ 0xc79585e3, __VMLINUX_SYMBOL_STR(snd_soc_rtdcom_lookup) },
	{ 0x5f31288f, __VMLINUX_SYMBOL_STR(ftrace_event_reg) },
	{ 0xb83f22a, __VMLINUX_SYMBOL_STR(sst_block_alloc_scratch) },
	{ 0xa8c06451, __VMLINUX_SYMBOL_STR(sst_dsp_ipc_msg_rx) },
	{ 0xedc95699, __VMLINUX_SYMBOL_STR(_dev_info) },
	{ 0x78764f4e, __VMLINUX_SYMBOL_STR(pv_irq_ops) },
	{ 0x4ed795dc, __VMLINUX_SYMBOL_STR(sst_module_runtime_alloc_blocks) },
	{ 0x42c8de35, __VMLINUX_SYMBOL_STR(ioremap_nocache) },
	{ 0xf90040c4, __VMLINUX_SYMBOL_STR(sst_fw_reload) },
	{ 0xf350d6c, __VMLINUX_SYMBOL_STR(pm_runtime_enable) },
	{ 0xf0fdf6cb, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0x3bd1b1f6, __VMLINUX_SYMBOL_STR(msecs_to_jiffies) },
	{ 0xd62c833f, __VMLINUX_SYMBOL_STR(schedule_timeout) },
	{ 0x39b3935a, __VMLINUX_SYMBOL_STR(sst_fw_unload) },
	{ 0x56bafc43, __VMLINUX_SYMBOL_STR(sst_module_alloc_blocks) },
	{ 0x7ed89fbf, __VMLINUX_SYMBOL_STR(devm_snd_soc_register_component) },
	{ 0x3d77dbe2, __VMLINUX_SYMBOL_STR(sst_module_free) },
	{ 0x2ea2c95c, __VMLINUX_SYMBOL_STR(__x86_indirect_thunk_rax) },
	{ 0xd2fe5067, __VMLINUX_SYMBOL_STR(snd_dma_free_pages) },
	{ 0xaf85d459, __VMLINUX_SYMBOL_STR(sst_ipc_tx_message_nowait) },
	{ 0x703b3d5d, __VMLINUX_SYMBOL_STR(snd_soc_suspend) },
	{ 0xa31ca72, __VMLINUX_SYMBOL_STR(sst_module_runtime_save) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
	{ 0x41ec4c1a, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0xe9020809, __VMLINUX_SYMBOL_STR(__dynamic_dev_dbg) },
	{ 0x9327f5ce, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irqsave) },
	{ 0x603dae35, __VMLINUX_SYMBOL_STR(sst_ipc_drop_all) },
	{ 0xcf21d241, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0xa8cd933b, __VMLINUX_SYMBOL_STR(sst_dsp_free) },
	{ 0x1e047854, __VMLINUX_SYMBOL_STR(warn_slowpath_fmt) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x69acdf38, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x71995c4e, __VMLINUX_SYMBOL_STR(trace_event_raw_init) },
	{ 0x5c8b5ce8, __VMLINUX_SYMBOL_STR(prepare_to_wait) },
	{ 0x7a7f7d68, __VMLINUX_SYMBOL_STR(dma_supported) },
	{ 0xedc03953, __VMLINUX_SYMBOL_STR(iounmap) },
	{ 0x42bb8d80, __VMLINUX_SYMBOL_STR(perf_trace_buf_prepare) },
	{ 0xf72f6314, __VMLINUX_SYMBOL_STR(sst_memcpy_fromio_32) },
	{ 0x850af17d, __VMLINUX_SYMBOL_STR(sst_fw_free_all) },
	{ 0xab831d49, __VMLINUX_SYMBOL_STR(sst_dsp_boot) },
	{ 0xbcfc0e4e, __VMLINUX_SYMBOL_STR(sst_module_runtime_free) },
	{ 0x7628f3c7, __VMLINUX_SYMBOL_STR(this_cpu_off) },
	{ 0x7e7c273f, __VMLINUX_SYMBOL_STR(request_firmware) },
	{ 0xfa66f77c, __VMLINUX_SYMBOL_STR(finish_wait) },
	{ 0x8a84a7b5, __VMLINUX_SYMBOL_STR(snd_pcm_lib_preallocate_pages_for_all) },
	{ 0xcace5945, __VMLINUX_SYMBOL_STR(pm_runtime_set_autosuspend_delay) },
	{ 0x41f54a0c, __VMLINUX_SYMBOL_STR(dev_warn) },
	{ 0x6af8e8e1, __VMLINUX_SYMBOL_STR(snd_soc_resume) },
	{ 0x3f3d2c92, __VMLINUX_SYMBOL_STR(sst_module_runtime_get_from_id) },
	{ 0x2e0d2f7f, __VMLINUX_SYMBOL_STR(queue_work_on) },
	{ 0x1e3a88fb, __VMLINUX_SYMBOL_STR(trace_seq_printf) },
	{ 0xa3897b7f, __VMLINUX_SYMBOL_STR(sst_ipc_tx_message_wait) },
	{ 0x79a66c5a, __VMLINUX_SYMBOL_STR(platform_driver_unregister) },
	{ 0xb4554c95, __VMLINUX_SYMBOL_STR(sst_block_free_scratch) },
	{ 0x8fdc1359, __VMLINUX_SYMBOL_STR(snd_soc_bytes_info_ext) },
	{ 0x3350e10b, __VMLINUX_SYMBOL_STR(sst_dsp_new) },
	{ 0x636462f8, __VMLINUX_SYMBOL_STR(devm_kmalloc) },
	{ 0x7cf5b2b3, __VMLINUX_SYMBOL_STR(dev_get_drvdata) },
	{ 0x4b55313f, __VMLINUX_SYMBOL_STR(ftrace_raw_output_prep) },
	{ 0xe315da4a, __VMLINUX_SYMBOL_STR(release_firmware) },
	{ 0x4e64392f, __VMLINUX_SYMBOL_STR(sst_module_runtime_free_blocks) },
	{ 0x584c5b17, __VMLINUX_SYMBOL_STR(dma_ops) },
	{ 0x498d293a, __VMLINUX_SYMBOL_STR(trace_buffer_unlock_commit) },
	{ 0xe914e41e, __VMLINUX_SYMBOL_STR(strcpy) },
	{ 0x17fbce60, __VMLINUX_SYMBOL_STR(sme_me_mask) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=snd-soc-sst-firmware,snd-soc-sst-dsp,snd-pcm,snd-soc-core,snd-soc-sst-ipc,snd";


MODULE_INFO(srcversion, "6509C0AF49537F67A4D1AA9");
MODULE_INFO(rhelversion, "7.7");
#ifdef RETPOLINE
	MODULE_INFO(retpoline, "Y");
#endif
#ifdef CONFIG_MPROFILE_KERNEL
	MODULE_INFO(mprofile, "Y");
#endif
