#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x28950ef1, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x9133ff34, __VMLINUX_SYMBOL_STR(devlink_dpipe_entry_ctx_append) },
	{ 0x2d3385d3, __VMLINUX_SYMBOL_STR(system_wq) },
	{ 0x92a1ee7d, __VMLINUX_SYMBOL_STR(neigh_lookup) },
	{ 0xa77bfd29, __VMLINUX_SYMBOL_STR(register_inet6addr_validator_notifier) },
	{ 0xa7de1d69, __VMLINUX_SYMBOL_STR(netdev_info) },
	{ 0x66f87150, __VMLINUX_SYMBOL_STR(register_netdevice_notifier_rh) },
	{ 0x98ab5c8d, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0xd2b09ce5, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0x4d82b75a, __VMLINUX_SYMBOL_STR(mlxsw_afk_encode) },
	{ 0x86767ac, __VMLINUX_SYMBOL_STR(devlink_dpipe_match_put) },
	{ 0x1ed8b599, __VMLINUX_SYMBOL_STR(__x86_indirect_thunk_r8) },
	{ 0x19fa5852, __VMLINUX_SYMBOL_STR(mlxsw_core_flush_owq) },
	{ 0x87876323, __VMLINUX_SYMBOL_STR(mlxsw_afk_values_add_buf) },
	{ 0x858c30d0, __VMLINUX_SYMBOL_STR(mlxsw_afa_block_create) },
	{ 0xaee87ee1, __VMLINUX_SYMBOL_STR(rht_bucket_nested) },
	{ 0xbf181dfe, __VMLINUX_SYMBOL_STR(tcf_block_cb_decref) },
	{ 0xa9b430bf, __VMLINUX_SYMBOL_STR(mlxsw_core_res_valid) },
	{ 0x15801382, __VMLINUX_SYMBOL_STR(mlxsw_afk_key_info_put) },
	{ 0x8f3d48ae, __VMLINUX_SYMBOL_STR(devlink_dpipe_table_register) },
	{ 0x8408b85a, __VMLINUX_SYMBOL_STR(tcf_block_cb_lookup) },
	{ 0xcd064321, __VMLINUX_SYMBOL_STR(mlxsw_core_port_clear) },
	{ 0xc32c71af, __VMLINUX_SYMBOL_STR(register_inetaddr_validator_notifier) },
	{ 0x8cf062de, __VMLINUX_SYMBOL_STR(mlxsw_afa_block_append_vlan_modify) },
	{ 0xbeef990f, __VMLINUX_SYMBOL_STR(devlink_sb_unregister) },
	{ 0x754d539c, __VMLINUX_SYMBOL_STR(strlen) },
	{ 0xea124bd1, __VMLINUX_SYMBOL_STR(gcd) },
	{ 0x253ef8c, __VMLINUX_SYMBOL_STR(skb_pad) },
	{ 0xf68285c0, __VMLINUX_SYMBOL_STR(register_inetaddr_notifier) },
	{ 0x26e19796, __VMLINUX_SYMBOL_STR(vlan_dev_vlan_id) },
	{ 0x79aa04a2, __VMLINUX_SYMBOL_STR(get_random_bytes) },
	{ 0xab63baa5, __VMLINUX_SYMBOL_STR(unregister_inetaddr_validator_notifier) },
	{ 0x70c0f512, __VMLINUX_SYMBOL_STR(mlxsw_afa_block_append_mcrouter) },
	{ 0xfc1dc1ba, __VMLINUX_SYMBOL_STR(netdev_walk_all_lower_dev) },
	{ 0xa6c0831d, __VMLINUX_SYMBOL_STR(devlink_dpipe_entry_ctx_close) },
	{ 0xc7a4fbed, __VMLINUX_SYMBOL_STR(rtnl_lock) },
	{ 0x3c6b5572, __VMLINUX_SYMBOL_STR(vlan_uses_dev) },
	{ 0x7e8ba329, __VMLINUX_SYMBOL_STR(arp_tbl) },
	{ 0xdc415cf1, __VMLINUX_SYMBOL_STR(mlxsw_afa_block_continue) },
	{ 0xb5ff38e0, __VMLINUX_SYMBOL_STR(mlxsw_core_lag_mapping_set) },
	{ 0x12b78cf1, __VMLINUX_SYMBOL_STR(netdev_has_any_upper_dev) },
	{ 0x7028aa99, __VMLINUX_SYMBOL_STR(netif_carrier_on) },
	{ 0x9d633750, __VMLINUX_SYMBOL_STR(dst_release) },
	{ 0x1637ff0f, __VMLINUX_SYMBOL_STR(_raw_spin_lock_bh) },
	{ 0x618a30ab, __VMLINUX_SYMBOL_STR(mlxsw_afa_block_commit) },
	{ 0xf75e6dd1, __VMLINUX_SYMBOL_STR(__tcf_block_cb_register) },
	{ 0xa1e8c9c7, __VMLINUX_SYMBOL_STR(devlink_resource_size_get) },
	{ 0xc0a3d105, __VMLINUX_SYMBOL_STR(find_next_bit) },
	{ 0x5694a341, __VMLINUX_SYMBOL_STR(mlxsw_afa_block_append_fid_set) },
	{ 0x6b06fdce, __VMLINUX_SYMBOL_STR(delayed_work_timer_fn) },
	{ 0xa1f9a134, __VMLINUX_SYMBOL_STR(__x86_indirect_thunk_rsi) },
	{ 0xbfe4f83a, __VMLINUX_SYMBOL_STR(netif_carrier_off) },
	{ 0x114a9d69, __VMLINUX_SYMBOL_STR(netdev_master_upper_dev_get) },
	{ 0xbfb7df3c, __VMLINUX_SYMBOL_STR(mlxsw_core_driver_priv) },
	{ 0x60352082, __VMLINUX_SYMBOL_STR(register_inet6addr_notifier) },
	{ 0xf087137d, __VMLINUX_SYMBOL_STR(__dynamic_pr_debug) },
	{ 0x448eac3e, __VMLINUX_SYMBOL_STR(kmemdup) },
	{ 0x500a096f, __VMLINUX_SYMBOL_STR(__tcf_block_cb_unregister) },
	{ 0xc29957c3, __VMLINUX_SYMBOL_STR(__x86_indirect_thunk_rcx) },
	{ 0xc12ed120, __VMLINUX_SYMBOL_STR(mlxsw_afk_create) },
	{ 0x5379619e, __VMLINUX_SYMBOL_STR(mlxsw_afa_block_append_allocated_counter) },
	{ 0x39a96739, __VMLINUX_SYMBOL_STR(mlxsw_core_lag_mapping_clear) },
	{ 0xf8071e5e, __VMLINUX_SYMBOL_STR(__dev_kfree_skb_any) },
	{ 0x593a99b, __VMLINUX_SYMBOL_STR(init_timer_key) },
	{ 0xc3e2d892, __VMLINUX_SYMBOL_STR(parman_create) },
	{ 0x797c8fa9, __VMLINUX_SYMBOL_STR(cancel_delayed_work_sync) },
	{ 0xe0a880ee, __VMLINUX_SYMBOL_STR(br_multicast_enabled) },
	{ 0xf76df3e2, __VMLINUX_SYMBOL_STR(mlxsw_afa_block_append_drop) },
	{ 0x88e3b639, __VMLINUX_SYMBOL_STR(neigh_destroy) },
	{ 0x47c65bfc, __VMLINUX_SYMBOL_STR(unregister_inet6addr_validator_notifier) },
	{ 0xf54e4264, __VMLINUX_SYMBOL_STR(devlink_dpipe_table_unregister) },
	{ 0x8231dd28, __VMLINUX_SYMBOL_STR(mlxsw_core_trap_register) },
	{ 0x674187c7, __VMLINUX_SYMBOL_STR(mlxsw_core_driver_unregister) },
	{ 0x3bd7d704, __VMLINUX_SYMBOL_STR(skb_realloc_headroom) },
	{ 0x53424ac5, __VMLINUX_SYMBOL_STR(rhashtable_insert_slow) },
	{ 0xcc31f329, __VMLINUX_SYMBOL_STR(mlxsw_core_port_init) },
	{ 0x384930cf, __VMLINUX_SYMBOL_STR(mlxsw_afa_block_append_trap) },
	{ 0x670b8e88, __VMLINUX_SYMBOL_STR(netdev_walk_all_upper_dev_rcu) },
	{ 0xfd799a84, __VMLINUX_SYMBOL_STR(__neigh_create) },
	{ 0xbd4dd9f3, __VMLINUX_SYMBOL_STR(devlink_dpipe_entry_clear) },
	{ 0x7d11c268, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0xc9ec4e21, __VMLINUX_SYMBOL_STR(free_percpu) },
	{ 0x6840cbd6, __VMLINUX_SYMBOL_STR(__dynamic_netdev_dbg) },
	{ 0x343a1a8, __VMLINUX_SYMBOL_STR(__list_add) },
	{ 0xd990e0cb, __VMLINUX_SYMBOL_STR(devlink_dpipe_headers_register) },
	{ 0xa4b6ce8c, __VMLINUX_SYMBOL_STR(mlxsw_afa_block_append_counter) },
	{ 0x618bef18, __VMLINUX_SYMBOL_STR(__neigh_event_send) },
	{ 0xbb97f6d3, __VMLINUX_SYMBOL_STR(mlxsw_pci_driver_register) },
	{ 0x44f2bfbf, __VMLINUX_SYMBOL_STR(rhashtable_destroy) },
	{ 0x63874d4c, __VMLINUX_SYMBOL_STR(mlxsw_core_port_driver_priv) },
	{ 0xad645234, __VMLINUX_SYMBOL_STR(register_switchdev_notifier) },
	{ 0x21a6087d, __VMLINUX_SYMBOL_STR(mlxsw_afk_key_info_subset) },
	{ 0xfe7c4287, __VMLINUX_SYMBOL_STR(nr_cpu_ids) },
	{ 0x82bb04bb, __VMLINUX_SYMBOL_STR(mlxsw_pci_driver_unregister) },
	{ 0x2fe252cc, __VMLINUX_SYMBOL_STR(unregister_inet6addr_notifier) },
	{ 0x7224fcd8, __VMLINUX_SYMBOL_STR(rht_bucket_nested_insert) },
	{ 0xfb578fc5, __VMLINUX_SYMBOL_STR(memset) },
	{ 0xca34ccf, __VMLINUX_SYMBOL_STR(mlxsw_core_max_ports) },
	{ 0x1d4519c, __VMLINUX_SYMBOL_STR(dev_err) },
	{ 0x37befc70, __VMLINUX_SYMBOL_STR(jiffies_to_msecs) },
	{ 0x2637f15a, __VMLINUX_SYMBOL_STR(ipmr_cache_free) },
	{ 0x6d294e43, __VMLINUX_SYMBOL_STR(clock_t_to_jiffies) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x532894bc, __VMLINUX_SYMBOL_STR(ethtool_op_get_link) },
	{ 0x3f4662bc, __VMLINUX_SYMBOL_STR(mlxsw_afk_values_add_u32) },
	{ 0x980783de, __VMLINUX_SYMBOL_STR(devlink_resource_occ_get_register) },
	{ 0x449ad0a7, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0xf23c8923, __VMLINUX_SYMBOL_STR(mlxsw_afa_create) },
	{ 0x479c3c86, __VMLINUX_SYMBOL_STR(find_next_zero_bit) },
	{ 0xa780a44, __VMLINUX_SYMBOL_STR(free_netdev) },
	{ 0xe7b00dfb, __VMLINUX_SYMBOL_STR(__x86_indirect_thunk_r13) },
	{ 0xfc3bba0f, __VMLINUX_SYMBOL_STR(unregister_fib_notifier) },
	{ 0x5948f2f0, __VMLINUX_SYMBOL_STR(register_netdev) },
	{ 0xc0b2664d, __VMLINUX_SYMBOL_STR(devlink_dpipe_header_ipv4) },
	{ 0xfb4e23d9, __VMLINUX_SYMBOL_STR(netif_receive_skb) },
	{ 0xc6a3d260, __VMLINUX_SYMBOL_STR(parman_prio_fini) },
	{ 0x5792f848, __VMLINUX_SYMBOL_STR(strlcpy) },
	{ 0x4fe1eddf, __VMLINUX_SYMBOL_STR(unregister_netevent_notifier) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0x51f677f4, __VMLINUX_SYMBOL_STR(skb_push) },
	{ 0xd357120b, __VMLINUX_SYMBOL_STR(mlxfw_firmware_flash) },
	{ 0x521445b, __VMLINUX_SYMBOL_STR(list_del) },
	{ 0xa4f88abb, __VMLINUX_SYMBOL_STR(fib4_rule_default) },
	{ 0xa1a12204, __VMLINUX_SYMBOL_STR(mlxsw_core_port_eth_set) },
	{ 0x58a63f85, __VMLINUX_SYMBOL_STR(mlxsw_reg_trans_query) },
	{ 0x42872584, __VMLINUX_SYMBOL_STR(devlink_dpipe_headers_unregister) },
	{ 0xe234e34, __VMLINUX_SYMBOL_STR(nd_tbl) },
	{ 0x62a2c704, __VMLINUX_SYMBOL_STR(devlink_dpipe_entry_ctx_prepare) },
	{ 0x9cbf026d, __VMLINUX_SYMBOL_STR(mlxsw_afa_destroy) },
	{ 0x8b7e26f5, __VMLINUX_SYMBOL_STR(parman_item_remove) },
	{ 0xdcca836e, __VMLINUX_SYMBOL_STR(init_net) },
	{ 0x67d8b281, __VMLINUX_SYMBOL_STR(__dev_get_by_index) },
	{ 0x5ff17b5c, __VMLINUX_SYMBOL_STR(mlxsw_afa_block_destroy) },
	{ 0x86971169, __VMLINUX_SYMBOL_STR(vlan_dev_real_dev) },
	{ 0x5b910ca5, __VMLINUX_SYMBOL_STR(tcf_block_cb_priv) },
	{ 0xf11543ff, __VMLINUX_SYMBOL_STR(find_first_zero_bit) },
	{ 0x8b8837ba, __VMLINUX_SYMBOL_STR(ip6_route_output) },
	{ 0xbd671048, __VMLINUX_SYMBOL_STR(__alloc_percpu_gfp) },
	{ 0xec51e246, __VMLINUX_SYMBOL_STR(mlxsw_core_skb_transmit_busy) },
	{ 0x2e9cbb08, __VMLINUX_SYMBOL_STR(ipmr_rule_default) },
	{ 0xea7e31ba, __VMLINUX_SYMBOL_STR(free_fib_info) },
	{ 0x5f2d7b40, __VMLINUX_SYMBOL_STR(mlxsw_core_driver_register) },
	{ 0xb40321ef, __VMLINUX_SYMBOL_STR(mlxsw_afa_block_append_fwd) },
	{ 0xedc95699, __VMLINUX_SYMBOL_STR(_dev_info) },
	{ 0xb601be4c, __VMLINUX_SYMBOL_STR(__x86_indirect_thunk_rdx) },
	{ 0xfe029963, __VMLINUX_SYMBOL_STR(unregister_inetaddr_notifier) },
	{ 0xbf4680e4, __VMLINUX_SYMBOL_STR(devlink_resource_register) },
	{ 0x141e6a0d, __VMLINUX_SYMBOL_STR(mlxsw_core_port_fini) },
	{ 0xba63339c, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_bh) },
	{ 0xf0fdf6cb, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0xc311ec22, __VMLINUX_SYMBOL_STR(cpu_possible_mask) },
	{ 0x43a9b87e, __VMLINUX_SYMBOL_STR(mlxsw_afa_block_terminate) },
	{ 0x3bd1b1f6, __VMLINUX_SYMBOL_STR(msecs_to_jiffies) },
	{ 0xf518717, __VMLINUX_SYMBOL_STR(parman_prio_init) },
	{ 0x7cb1aea1, __VMLINUX_SYMBOL_STR(devlink_dpipe_header_ethernet) },
	{ 0x155f4108, __VMLINUX_SYMBOL_STR(___ratelimit) },
	{ 0x945e358e, __VMLINUX_SYMBOL_STR(devlink_dpipe_action_put) },
	{ 0x10c0dec6, __VMLINUX_SYMBOL_STR(ip6_tnl_xmit_ctl) },
	{ 0x1fbd16da, __VMLINUX_SYMBOL_STR(ip_tos2prio) },
	{ 0xf28404cf, __VMLINUX_SYMBOL_STR(devlink_dpipe_header_ipv6) },
	{ 0x19428dd6, __VMLINUX_SYMBOL_STR(unregister_netdevice_notifier_rh) },
	{ 0xdc776276, __VMLINUX_SYMBOL_STR(mlxsw_afa_block_jump) },
	{ 0x6b2dc060, __VMLINUX_SYMBOL_STR(dump_stack) },
	{ 0x3ecaa08a, __VMLINUX_SYMBOL_STR(devlink_dpipe_table_counter_enabled) },
	{ 0xca39ae6a, __VMLINUX_SYMBOL_STR(parman_destroy) },
	{ 0x2ea2c95c, __VMLINUX_SYMBOL_STR(__x86_indirect_thunk_rax) },
	{ 0x63fedd30, __VMLINUX_SYMBOL_STR(eth_type_trans) },
	{ 0xb8f524ab, __VMLINUX_SYMBOL_STR(rt6_rcu_free) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
	{ 0xa0f3b7a1, __VMLINUX_SYMBOL_STR(netdev_err) },
	{ 0xab0c687, __VMLINUX_SYMBOL_STR(mlxsw_core_lag_mapping_get) },
	{ 0x65924258, __VMLINUX_SYMBOL_STR(mlxsw_core_res_get) },
	{ 0xe503a449, __VMLINUX_SYMBOL_STR(mlxsw_afa_block_append_trap_and_forward) },
	{ 0x41ec4c1a, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x1d533679, __VMLINUX_SYMBOL_STR(rt6_free_pcpu) },
	{ 0x996c5d6d, __VMLINUX_SYMBOL_STR(mlxsw_reg_trans_bulk_wait) },
	{ 0xd94cc09, __VMLINUX_SYMBOL_STR(__per_cpu_offset) },
	{ 0x6fc1e749, __VMLINUX_SYMBOL_STR(devlink_dpipe_table_resource_set) },
	{ 0xb32ff9a, __VMLINUX_SYMBOL_STR(ip_route_output_flow) },
	{ 0x1b7e9e74, __VMLINUX_SYMBOL_STR(mlxsw_core_schedule_dw) },
	{ 0x5c04acc5, __VMLINUX_SYMBOL_STR(netdev_warn) },
	{ 0x10108897, __VMLINUX_SYMBOL_STR(rhashtable_init) },
	{ 0x1e047854, __VMLINUX_SYMBOL_STR(warn_slowpath_fmt) },
	{ 0xeda0acca, __VMLINUX_SYMBOL_STR(tcf_block_cb_unregister) },
	{ 0xf82d22c9, __VMLINUX_SYMBOL_STR(mlxsw_afk_key_info_block_encoding_get) },
	{ 0xc877477e, __VMLINUX_SYMBOL_STR(tcf_block_cb_incref) },
	{ 0xa5a99b49, __VMLINUX_SYMBOL_STR(_raw_read_lock_bh) },
	{ 0xbded85d0, __VMLINUX_SYMBOL_STR(_raw_read_unlock_bh) },
	{ 0x6d27ef64, __VMLINUX_SYMBOL_STR(__bitmap_empty) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0xee747a31, __VMLINUX_SYMBOL_STR(psample_sample_packet) },
	{ 0xe723243f, __VMLINUX_SYMBOL_STR(mlxsw_core_schedule_work) },
	{ 0x3fa81d1, __VMLINUX_SYMBOL_STR(devlink_sb_register) },
	{ 0x69acdf38, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0xe2b3207a, __VMLINUX_SYMBOL_STR(unregister_switchdev_notifier) },
	{ 0x354b044, __VMLINUX_SYMBOL_STR(mlxsw_core_trap_unregister) },
	{ 0x47041e4e, __VMLINUX_SYMBOL_STR(mlxsw_afk_key_info_blocks_count_get) },
	{ 0x7628f3c7, __VMLINUX_SYMBOL_STR(this_cpu_off) },
	{ 0x7bed4cbc, __VMLINUX_SYMBOL_STR(mlxsw_afk_key_info_get) },
	{ 0x7b03d378, __VMLINUX_SYMBOL_STR(parman_item_add) },
	{ 0x7e7c273f, __VMLINUX_SYMBOL_STR(request_firmware) },
	{ 0xb352177e, __VMLINUX_SYMBOL_STR(find_first_bit) },
	{ 0xca15d13a, __VMLINUX_SYMBOL_STR(br_multicast_router) },
	{ 0x41f54a0c, __VMLINUX_SYMBOL_STR(dev_warn) },
	{ 0x64d6bea2, __VMLINUX_SYMBOL_STR(unregister_netdev) },
	{ 0xb58a4052, __VMLINUX_SYMBOL_STR(fib6_rule_default) },
	{ 0xee8a3880, __VMLINUX_SYMBOL_STR(mlxsw_reg_query) },
	{ 0x93a99dbc, __VMLINUX_SYMBOL_STR(alloc_etherdev_mqs_rh) },
	{ 0x2e0d2f7f, __VMLINUX_SYMBOL_STR(queue_work_on) },
	{ 0x28318305, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0x81553ad8, __VMLINUX_SYMBOL_STR(consume_skb) },
	{ 0x6cff3b90, __VMLINUX_SYMBOL_STR(register_fib_notifier) },
	{ 0x85670f1d, __VMLINUX_SYMBOL_STR(rtnl_is_locked) },
	{ 0x4761f17c, __VMLINUX_SYMBOL_STR(register_netevent_notifier) },
	{ 0xbaa3e574, __VMLINUX_SYMBOL_STR(call_switchdev_notifiers) },
	{ 0xe81c09c, __VMLINUX_SYMBOL_STR(mlxsw_afk_destroy) },
	{ 0x829e8851, __VMLINUX_SYMBOL_STR(mlxsw_afa_block_first_set) },
	{ 0xf19a8136, __VMLINUX_SYMBOL_STR(mlxsw_afa_block_append_mirror) },
	{ 0x5fe309fd, __VMLINUX_SYMBOL_STR(netdev_walk_all_lower_dev_rcu) },
	{ 0xe315da4a, __VMLINUX_SYMBOL_STR(release_firmware) },
	{ 0xd542439, __VMLINUX_SYMBOL_STR(__ipv6_addr_type) },
	{ 0x4816904a, __VMLINUX_SYMBOL_STR(mlxsw_core_skb_transmit) },
	{ 0x6e720ff2, __VMLINUX_SYMBOL_STR(rtnl_unlock) },
	{ 0x68a6682a, __VMLINUX_SYMBOL_STR(tcf_block_cb_register) },
	{ 0xd87db068, __VMLINUX_SYMBOL_STR(br_vlan_enabled) },
	{ 0x65427447, __VMLINUX_SYMBOL_STR(devlink_resource_occ_get_unregister) },
	{ 0xcadb6b2a, __VMLINUX_SYMBOL_STR(netdev_lower_get_next) },
	{ 0xf7d733e8, __VMLINUX_SYMBOL_STR(mlxsw_reg_write) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=devlink,mlxsw_core,parman,bridge,mlxsw_pci,mlxfw,ip6_tunnel,psample";

MODULE_ALIAS("pci:v000015B3d0000CB84sv*sd*bc*sc*i*");

MODULE_INFO(srcversion, "0FFF35B4C7808F2C87BBEE9");
MODULE_INFO(rhelversion, "7.7");
#ifdef RETPOLINE
	MODULE_INFO(retpoline, "Y");
#endif
#ifdef CONFIG_MPROFILE_KERNEL
	MODULE_INFO(mprofile, "Y");
#endif
