#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x28950ef1, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x9a0d63fa, __VMLINUX_SYMBOL_STR(blkdev_issue_discard) },
	{ 0xacfa5975, __VMLINUX_SYMBOL_STR(kmem_cache_destroy) },
	{ 0x98ab5c8d, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x65e75cb6, __VMLINUX_SYMBOL_STR(__list_del_entry) },
	{ 0x405c1144, __VMLINUX_SYMBOL_STR(get_seconds) },
	{ 0x7129e5f8, __VMLINUX_SYMBOL_STR(hex_asc) },
	{ 0x1299cf0f, __VMLINUX_SYMBOL_STR(sb_min_blocksize) },
	{ 0x1ed8b599, __VMLINUX_SYMBOL_STR(__x86_indirect_thunk_r8) },
	{ 0x24a5d9bf, __VMLINUX_SYMBOL_STR(mark_buffer_dirty_inode) },
	{ 0xf5893abf, __VMLINUX_SYMBOL_STR(up_read) },
	{ 0xe063f03d, __VMLINUX_SYMBOL_STR(__bread) },
	{ 0x4c4fef19, __VMLINUX_SYMBOL_STR(kernel_stack) },
	{ 0x5d43e8d3, __VMLINUX_SYMBOL_STR(unload_nls) },
	{ 0xc821665c, __VMLINUX_SYMBOL_STR(generic_file_llseek) },
	{ 0x69c74a2b, __VMLINUX_SYMBOL_STR(__mark_inode_dirty) },
	{ 0x784213a6, __VMLINUX_SYMBOL_STR(pv_lock_ops) },
	{ 0x4b7dcf38, __VMLINUX_SYMBOL_STR(_raw_qspin_lock) },
	{ 0x60a13e90, __VMLINUX_SYMBOL_STR(rcu_barrier) },
	{ 0x8e0d2ce2, __VMLINUX_SYMBOL_STR(from_kuid_munged) },
	{ 0x815b5dd4, __VMLINUX_SYMBOL_STR(match_octal) },
	{ 0x64999478, __VMLINUX_SYMBOL_STR(congestion_wait) },
	{ 0x92a9c60c, __VMLINUX_SYMBOL_STR(time_to_tm) },
	{ 0xca5bd896, __VMLINUX_SYMBOL_STR(generic_fh_to_parent) },
	{ 0x50612798, __VMLINUX_SYMBOL_STR(seq_puts) },
	{ 0xacf4d843, __VMLINUX_SYMBOL_STR(match_strdup) },
	{ 0xcae232b, __VMLINUX_SYMBOL_STR(utf16s_to_utf8s) },
	{ 0xf3108d14, __VMLINUX_SYMBOL_STR(generic_file_aio_read) },
	{ 0x74df1d4, __VMLINUX_SYMBOL_STR(seq_printf) },
	{ 0x6729d3df, __VMLINUX_SYMBOL_STR(__get_user_4) },
	{ 0x44e9a829, __VMLINUX_SYMBOL_STR(match_token) },
	{ 0x72dea5ce, __VMLINUX_SYMBOL_STR(init_user_ns) },
	{ 0xba27d204, __VMLINUX_SYMBOL_STR(names_cachep) },
	{ 0xba41d0a3, __VMLINUX_SYMBOL_STR(filemap_fdatawait_range) },
	{ 0x4ed12f73, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x85df9b6c, __VMLINUX_SYMBOL_STR(strsep) },
	{ 0x7f9ad7a0, __VMLINUX_SYMBOL_STR(generic_read_dir) },
	{ 0xde4fab67, __VMLINUX_SYMBOL_STR(igrab) },
	{ 0x91715312, __VMLINUX_SYMBOL_STR(sprintf) },
	{ 0xf08c1f24, __VMLINUX_SYMBOL_STR(generic_file_aio_write) },
	{ 0x343a1a8, __VMLINUX_SYMBOL_STR(__list_add) },
	{ 0x2f4c181a, __VMLINUX_SYMBOL_STR(truncate_setsize) },
	{ 0x57a6ccd0, __VMLINUX_SYMBOL_STR(down_read) },
	{ 0xe6788b5d, __VMLINUX_SYMBOL_STR(from_kgid_munged) },
	{ 0x41972754, __VMLINUX_SYMBOL_STR(make_kgid) },
	{ 0x71de9b3f, __VMLINUX_SYMBOL_STR(_copy_to_user) },
	{ 0x257ee9ad, __VMLINUX_SYMBOL_STR(__insert_inode_hash) },
	{ 0x5ae7445f, __VMLINUX_SYMBOL_STR(mpage_readpages) },
	{ 0xb8e7ce2c, __VMLINUX_SYMBOL_STR(__put_user_8) },
	{ 0xfb578fc5, __VMLINUX_SYMBOL_STR(memset) },
	{ 0x6c9eb947, __VMLINUX_SYMBOL_STR(mpage_readpage) },
	{ 0xb8c7ff88, __VMLINUX_SYMBOL_STR(current_task) },
	{ 0xafbf00ce, __VMLINUX_SYMBOL_STR(current_fs_time) },
	{ 0x9a025cd5, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x221201db, __VMLINUX_SYMBOL_STR(d_obtain_alias) },
	{ 0x449ad0a7, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0x52d065ef, __VMLINUX_SYMBOL_STR(write_inode_now) },
	{ 0x7c1372e8, __VMLINUX_SYMBOL_STR(panic) },
	{ 0xa90d3cd7, __VMLINUX_SYMBOL_STR(mpage_writepages) },
	{ 0xa1c76e0a, __VMLINUX_SYMBOL_STR(_cond_resched) },
	{ 0x5a921311, __VMLINUX_SYMBOL_STR(strncmp) },
	{ 0x19ee3d71, __VMLINUX_SYMBOL_STR(kmem_cache_free) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0xc3aaf0a9, __VMLINUX_SYMBOL_STR(__put_user_1) },
	{ 0x9abdea30, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0xfd5cf105, __VMLINUX_SYMBOL_STR(set_nlink) },
	{ 0x40ccf25c, __VMLINUX_SYMBOL_STR(__wait_on_buffer) },
	{ 0x2677c1b1, __VMLINUX_SYMBOL_STR(setattr_copy) },
	{ 0x3eb351fa, __VMLINUX_SYMBOL_STR(sync_dirty_buffer) },
	{ 0xfe3d5457, __VMLINUX_SYMBOL_STR(truncate_pagecache) },
	{ 0x4e3567f7, __VMLINUX_SYMBOL_STR(match_int) },
	{ 0x3b4ceb4a, __VMLINUX_SYMBOL_STR(up_write) },
	{ 0xe6e3b875, __VMLINUX_SYMBOL_STR(down_write) },
	{ 0x872fc991, __VMLINUX_SYMBOL_STR(__brelse) },
	{ 0xfe5d4bb2, __VMLINUX_SYMBOL_STR(sys_tz) },
	{ 0x35d4cd9f, __VMLINUX_SYMBOL_STR(__fsnotify_parent) },
	{ 0x4f6d74cf, __VMLINUX_SYMBOL_STR(inode_init_once) },
	{ 0x5c198c6f, __VMLINUX_SYMBOL_STR(mnt_drop_write_file) },
	{ 0xc6cbbc89, __VMLINUX_SYMBOL_STR(capable) },
	{ 0xbf0410cd, __VMLINUX_SYMBOL_STR(invalidate_inode_buffers) },
	{ 0xd11b7a3e, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0x972d5d67, __VMLINUX_SYMBOL_STR(ilookup) },
	{ 0xb2fd5ceb, __VMLINUX_SYMBOL_STR(__put_user_4) },
	{ 0xeabd94b0, __VMLINUX_SYMBOL_STR(sync_mapping_buffers) },
	{ 0x7fc02f17, __VMLINUX_SYMBOL_STR(generic_file_mmap) },
	{ 0x978c969f, __VMLINUX_SYMBOL_STR(block_write_full_page) },
	{ 0xce9b6ece, __VMLINUX_SYMBOL_STR(truncate_inode_pages_final) },
	{ 0x2a196e39, __VMLINUX_SYMBOL_STR(make_kuid) },
	{ 0x4d6daa40, __VMLINUX_SYMBOL_STR(generic_cont_expand_simple) },
	{ 0xfb2449f0, __VMLINUX_SYMBOL_STR(load_nls) },
	{ 0xf0fdf6cb, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0x155f4108, __VMLINUX_SYMBOL_STR(___ratelimit) },
	{ 0xfca3f8c8, __VMLINUX_SYMBOL_STR(generic_write_end) },
	{ 0xaf3f679e, __VMLINUX_SYMBOL_STR(__breadahead) },
	{ 0xdc2cbf2b, __VMLINUX_SYMBOL_STR(do_sync_read) },
	{ 0xdcf51fcb, __VMLINUX_SYMBOL_STR(mnt_want_write_file) },
	{ 0x8b8059bd, __VMLINUX_SYMBOL_STR(in_group_p) },
	{ 0x5e95b1cd, __VMLINUX_SYMBOL_STR(current_umask) },
	{ 0x2ea2c95c, __VMLINUX_SYMBOL_STR(__x86_indirect_thunk_rax) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
	{ 0xe4a8abdd, __VMLINUX_SYMBOL_STR(inode_change_ok) },
	{ 0x41ec4c1a, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x838ec443, __VMLINUX_SYMBOL_STR(sync_inode_metadata) },
	{ 0xaf5517a9, __VMLINUX_SYMBOL_STR(kmem_cache_create) },
	{ 0xe644f4ea, __VMLINUX_SYMBOL_STR(iput) },
	{ 0xd758dd03, __VMLINUX_SYMBOL_STR(cont_write_begin) },
	{ 0x11c05483, __VMLINUX_SYMBOL_STR(generic_file_fsync) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0xbf126881, __VMLINUX_SYMBOL_STR(iunique) },
	{ 0xb25db026, __VMLINUX_SYMBOL_STR(inode_dio_wait) },
	{ 0x9559e8eb, __VMLINUX_SYMBOL_STR(do_sync_write) },
	{ 0x69acdf38, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0xa75312bc, __VMLINUX_SYMBOL_STR(call_rcu_sched) },
	{ 0xf4a2d539, __VMLINUX_SYMBOL_STR(fsnotify) },
	{ 0xf9d26784, __VMLINUX_SYMBOL_STR(write_dirty_buffer) },
	{ 0xce605b1e, __VMLINUX_SYMBOL_STR(sb_set_blocksize) },
	{ 0xf05c7b8, __VMLINUX_SYMBOL_STR(__x86_indirect_thunk_r15) },
	{ 0xab9ea056, __VMLINUX_SYMBOL_STR(__bforget) },
	{ 0x46af2b76, __VMLINUX_SYMBOL_STR(d_make_root) },
	{ 0x9aba54e3, __VMLINUX_SYMBOL_STR(__blockdev_direct_IO) },
	{ 0x5a4896a8, __VMLINUX_SYMBOL_STR(__put_user_2) },
	{ 0x8989b72a, __VMLINUX_SYMBOL_STR(inode_needs_sync) },
	{ 0x43706ef3, __VMLINUX_SYMBOL_STR(filemap_fdatawrite_range) },
	{ 0xa04a9b5d, __VMLINUX_SYMBOL_STR(__find_get_block) },
	{ 0x6d4dfcf8, __VMLINUX_SYMBOL_STR(security_inode_setattr) },
	{ 0x5e14c0ee, __VMLINUX_SYMBOL_STR(mark_buffer_dirty) },
	{ 0xd434cca4, __VMLINUX_SYMBOL_STR(new_inode) },
	{ 0x52e938b2, __VMLINUX_SYMBOL_STR(generic_file_splice_read) },
	{ 0xbf3dbf85, __VMLINUX_SYMBOL_STR(__getblk) },
	{ 0x6a3da0af, __VMLINUX_SYMBOL_STR(generic_fh_to_dentry) },
	{ 0x913c50e8, __VMLINUX_SYMBOL_STR(clear_inode) },
	{ 0x2a6e6109, __VMLINUX_SYMBOL_STR(__init_rwsem) },
	{ 0x88db9f48, __VMLINUX_SYMBOL_STR(__check_object_size) },
	{ 0xfdb5cbba, __VMLINUX_SYMBOL_STR(filemap_flush) },
	{ 0x5776642c, __VMLINUX_SYMBOL_STR(generic_block_bmap) },
	{ 0x5f883970, __VMLINUX_SYMBOL_STR(generic_fillattr) },
	{ 0xa5ba588a, __VMLINUX_SYMBOL_STR(filemap_fdatawrite) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=";


MODULE_INFO(srcversion, "48C5E88500B6EBB832D91D7");
MODULE_INFO(rhelversion, "7.7");
#ifdef RETPOLINE
	MODULE_INFO(retpoline, "Y");
#endif
#ifdef CONFIG_MPROFILE_KERNEL
	MODULE_INFO(mprofile, "Y");
#endif
