#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x28950ef1, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0xe4151c38, __VMLINUX_SYMBOL_STR(drm_mode_get_hv_timing) },
	{ 0x6bc3fbc0, __VMLINUX_SYMBOL_STR(__unregister_chrdev) },
	{ 0x8487a2b6, __VMLINUX_SYMBOL_STR(flush_work) },
	{ 0x2d3385d3, __VMLINUX_SYMBOL_STR(system_wq) },
	{ 0x2689dbe0, __VMLINUX_SYMBOL_STR(drm_edid_get_monitor_name) },
	{ 0xd238e287, __VMLINUX_SYMBOL_STR(drm_atomic_get_connector_state) },
	{ 0xb43655eb, __VMLINUX_SYMBOL_STR(drm_bridge_mode_valid) },
	{ 0x3588d8ba, __VMLINUX_SYMBOL_STR(_raw_qspin_lock_irq) },
	{ 0x98ab5c8d, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x65e75cb6, __VMLINUX_SYMBOL_STR(__list_del_entry) },
	{ 0xd2b09ce5, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0xf9a482f9, __VMLINUX_SYMBOL_STR(msleep) },
	{ 0xfd60df2, __VMLINUX_SYMBOL_STR(drm_get_connector_status_name) },
	{ 0x4c4fef19, __VMLINUX_SYMBOL_STR(kernel_stack) },
	{ 0x38b92934, __VMLINUX_SYMBOL_STR(drm_calc_timestamping_constants) },
	{ 0x9dbfbd69, __VMLINUX_SYMBOL_STR(drm_get_edid) },
	{ 0x91fec1cc, __VMLINUX_SYMBOL_STR(drm_rect_calc_vscale) },
	{ 0xbe18153d, __VMLINUX_SYMBOL_STR(try_wait_for_completion) },
	{ 0x784213a6, __VMLINUX_SYMBOL_STR(pv_lock_ops) },
	{ 0x4b9a8e3c, __VMLINUX_SYMBOL_STR(drm_atomic_nonblocking_commit) },
	{ 0x4b7dcf38, __VMLINUX_SYMBOL_STR(_raw_qspin_lock) },
	{ 0x15692c87, __VMLINUX_SYMBOL_STR(param_ops_int) },
	{ 0xe6fd94e9, __VMLINUX_SYMBOL_STR(drm_format_info_block_height) },
	{ 0x33c48a26, __VMLINUX_SYMBOL_STR(drm_mode_validate_ycbcr420) },
	{ 0x47a52b75, __VMLINUX_SYMBOL_STR(drm_bridge_disable) },
	{ 0x3373abe7, __VMLINUX_SYMBOL_STR(drm_mode_create_from_cmdline_mode) },
	{ 0x91feedc2, __VMLINUX_SYMBOL_STR(dma_fence_release) },
	{ 0x1f81a0d8, __VMLINUX_SYMBOL_STR(framebuffer_release) },
	{ 0x3a41ebdb, __VMLINUX_SYMBOL_STR(drm_modeset_drop_locks) },
	{ 0xd94360c5, __VMLINUX_SYMBOL_STR(drm_atomic_set_fence_for_plane) },
	{ 0x646dcad6, __VMLINUX_SYMBOL_STR(drm_bridge_pre_enable) },
	{ 0xa717c399, __VMLINUX_SYMBOL_STR(unlink_framebuffer) },
	{ 0xbd85f4ff, __VMLINUX_SYMBOL_STR(drm_property_create_blob) },
	{ 0x686508ee, __VMLINUX_SYMBOL_STR(drm_mode_config_reset) },
	{ 0xc8b57c27, __VMLINUX_SYMBOL_STR(autoremove_wake_function) },
	{ 0x263ed23b, __VMLINUX_SYMBOL_STR(__x86_indirect_thunk_r12) },
	{ 0x9e445746, __VMLINUX_SYMBOL_STR(drm_atomic_state_clear) },
	{ 0x6156b8a2, __VMLINUX_SYMBOL_STR(drm_bridge_attach) },
	{ 0x20b789fe, __VMLINUX_SYMBOL_STR(drm_mode_destroy) },
	{ 0xf8993ddf, __VMLINUX_SYMBOL_STR(drm_property_blob_put) },
	{ 0xd4c14632, __VMLINUX_SYMBOL_STR(system_unbound_wq) },
	{ 0x50612798, __VMLINUX_SYMBOL_STR(seq_puts) },
	{ 0x4a93db25, __VMLINUX_SYMBOL_STR(drm_property_blob_get) },
	{ 0x4d974b9c, __VMLINUX_SYMBOL_STR(register_sysrq_key) },
	{ 0x7269938, __VMLINUX_SYMBOL_STR(drm_connector_set_tile_property) },
	{ 0x8d70d495, __VMLINUX_SYMBOL_STR(i2c_transfer) },
	{ 0x99dab631, __VMLINUX_SYMBOL_STR(drm_atomic_get_plane_state) },
	{ 0x3c63897, __VMLINUX_SYMBOL_STR(__drm_get_edid_firmware_path) },
	{ 0x5f92f539, __VMLINUX_SYMBOL_STR(fb_sys_read) },
	{ 0xf1421d13, __VMLINUX_SYMBOL_STR(drm_mode_sort) },
	{ 0x2c66300e, __VMLINUX_SYMBOL_STR(__rt_mutex_init) },
	{ 0x2d7e6127, __VMLINUX_SYMBOL_STR(drm_modeset_backoff) },
	{ 0x6b06fdce, __VMLINUX_SYMBOL_STR(delayed_work_timer_fn) },
	{ 0xdf566a59, __VMLINUX_SYMBOL_STR(__x86_indirect_thunk_r9) },
	{ 0x74df1d4, __VMLINUX_SYMBOL_STR(seq_printf) },
	{ 0x88bfa7e, __VMLINUX_SYMBOL_STR(cancel_work_sync) },
	{ 0x48259f91, __VMLINUX_SYMBOL_STR(device_destroy) },
	{ 0x448eac3e, __VMLINUX_SYMBOL_STR(kmemdup) },
	{ 0xc816cb3, __VMLINUX_SYMBOL_STR(__register_chrdev) },
	{ 0xc29957c3, __VMLINUX_SYMBOL_STR(__x86_indirect_thunk_rcx) },
	{ 0xeae3dfd6, __VMLINUX_SYMBOL_STR(__const_udelay) },
	{ 0xc6194f80, __VMLINUX_SYMBOL_STR(cfb_fillrect) },
	{ 0x1976aa06, __VMLINUX_SYMBOL_STR(param_ops_bool) },
	{ 0x593a99b, __VMLINUX_SYMBOL_STR(init_timer_key) },
	{ 0x797c8fa9, __VMLINUX_SYMBOL_STR(cancel_delayed_work_sync) },
	{ 0x17973e40, __VMLINUX_SYMBOL_STR(current_work) },
	{ 0x4ed12f73, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0xa215873f, __VMLINUX_SYMBOL_STR(drm_plane_force_disable) },
	{ 0x999e8297, __VMLINUX_SYMBOL_STR(vfree) },
	{ 0x26ed84b, __VMLINUX_SYMBOL_STR(drm_encoder_init) },
	{ 0xa2c74782, __VMLINUX_SYMBOL_STR(drm_modeset_acquire_fini) },
	{ 0x88b38c6c, __VMLINUX_SYMBOL_STR(drm_object_property_set_value) },
	{ 0x2e56e6b6, __VMLINUX_SYMBOL_STR(drm_connector_list_iter_next) },
	{ 0xe29e1d0e, __VMLINUX_SYMBOL_STR(out_of_line_wait_on_atomic_t) },
	{ 0x54efb5d6, __VMLINUX_SYMBOL_STR(cpu_number) },
	{ 0x3f469cb0, __VMLINUX_SYMBOL_STR(sys_copyarea) },
	{ 0x91715312, __VMLINUX_SYMBOL_STR(sprintf) },
	{ 0x60b40fd8, __VMLINUX_SYMBOL_STR(copy_user_enhanced_fast_string) },
	{ 0xffc6c87a, __VMLINUX_SYMBOL_STR(drm_detect_monitor_audio) },
	{ 0x8e82ea92, __VMLINUX_SYMBOL_STR(drm_universal_plane_init) },
	{ 0x7d11c268, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0x343a1a8, __VMLINUX_SYMBOL_STR(__list_add) },
	{ 0x1d6c788a, __VMLINUX_SYMBOL_STR(drm_get_format_info) },
	{ 0xf13ae361, __VMLINUX_SYMBOL_STR(drm_atomic_set_mode_prop_for_crtc) },
	{ 0xa6f8da46, __VMLINUX_SYMBOL_STR(i2c_add_adapter) },
	{ 0xe196a9f7, __VMLINUX_SYMBOL_STR(mutex_trylock) },
	{ 0x131db64a, __VMLINUX_SYMBOL_STR(system_long_wq) },
	{ 0xa9d0a50b, __VMLINUX_SYMBOL_STR(__drm_crtc_commit_free) },
	{ 0x2126ef0a, __VMLINUX_SYMBOL_STR(drm_client_release) },
	{ 0x1f5dc309, __VMLINUX_SYMBOL_STR(drm_atomic_set_mode_for_crtc) },
	{ 0x40256835, __VMLINUX_SYMBOL_STR(complete_all) },
	{ 0x30fcaa8e, __VMLINUX_SYMBOL_STR(fb_set_suspend) },
	{ 0xc631580a, __VMLINUX_SYMBOL_STR(console_unlock) },
	{ 0xf432dd3d, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0xcb2340b8, __VMLINUX_SYMBOL_STR(drm_rect_debug_print) },
	{ 0x31b8a5e3, __VMLINUX_SYMBOL_STR(__drm_set_edid_firmware_path) },
	{ 0xf9c0b663, __VMLINUX_SYMBOL_STR(strlcat) },
	{ 0x88ab6fe3, __VMLINUX_SYMBOL_STR(kgdb_active) },
	{ 0x1a67474b, __VMLINUX_SYMBOL_STR(drm_bridge_post_disable) },
	{ 0x15c361a2, __VMLINUX_SYMBOL_STR(drm_connector_update_edid_property) },
	{ 0x871ab41a, __VMLINUX_SYMBOL_STR(drm_rect_intersect) },
	{ 0xfb578fc5, __VMLINUX_SYMBOL_STR(memset) },
	{ 0x6e6614b8, __VMLINUX_SYMBOL_STR(drm_atomic_state_alloc) },
	{ 0xfa4aa72f, __VMLINUX_SYMBOL_STR(drm_mode_copy) },
	{ 0xd35c8b23, __VMLINUX_SYMBOL_STR(drm_atomic_commit) },
	{ 0xe1aff736, __VMLINUX_SYMBOL_STR(drm_mode_find_dmt) },
	{ 0xc85c81, __VMLINUX_SYMBOL_STR(drm_client_add) },
	{ 0xcb599f6b, __VMLINUX_SYMBOL_STR(cfb_imageblit) },
	{ 0x8f64aa4, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irqrestore) },
	{ 0xc770d15c, __VMLINUX_SYMBOL_STR(idr_alloc_cyclic) },
	{ 0xb8c7ff88, __VMLINUX_SYMBOL_STR(current_task) },
	{ 0xf209143e, __VMLINUX_SYMBOL_STR(drm_crtc_vblank_put) },
	{ 0x1698661c, __VMLINUX_SYMBOL_STR(drm_bridge_enable) },
	{ 0x9a025cd5, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x1b12fcb9, __VMLINUX_SYMBOL_STR(drm_object_attach_property) },
	{ 0xf61f8609, __VMLINUX_SYMBOL_STR(drm_mode_duplicate) },
	{ 0x7a890c8, __VMLINUX_SYMBOL_STR(fb_alloc_cmap) },
	{ 0x30a4cc09, __VMLINUX_SYMBOL_STR(drm_crtc_init_with_planes) },
	{ 0x449ad0a7, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0x6e30ba8e, __VMLINUX_SYMBOL_STR(drm_rect_rotate_inv) },
	{ 0xe5772d4a, __VMLINUX_SYMBOL_STR(copy_user_generic_string) },
	{ 0xa8621c5e, __VMLINUX_SYMBOL_STR(drm_atomic_set_crtc_for_connector) },
	{ 0x39c33912, __VMLINUX_SYMBOL_STR(drm_gem_handle_create) },
	{ 0x1ae7df04, __VMLINUX_SYMBOL_STR(drm_gem_object_put_unlocked) },
	{ 0x15ddbdc, __VMLINUX_SYMBOL_STR(wait_for_completion_interruptible) },
	{ 0xbf0bd23, __VMLINUX_SYMBOL_STR(register_framebuffer) },
	{ 0xc80c596e, __VMLINUX_SYMBOL_STR(fixed_size_llseek) },
	{ 0xfbaaf01e, __VMLINUX_SYMBOL_STR(console_lock) },
	{ 0x5792f848, __VMLINUX_SYMBOL_STR(strlcpy) },
	{ 0x593c1bac, __VMLINUX_SYMBOL_STR(__x86_indirect_thunk_rbx) },
	{ 0x75f149d0, __VMLINUX_SYMBOL_STR(drm_format_info_block_width) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0x9abdea30, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x521445b, __VMLINUX_SYMBOL_STR(list_del) },
	{ 0x2fd4b076, __VMLINUX_SYMBOL_STR(device_create) },
	{ 0x8df92f66, __VMLINUX_SYMBOL_STR(memchr_inv) },
	{ 0xabbd8851, __VMLINUX_SYMBOL_STR(drm_atomic_set_fb_for_plane) },
	{ 0x637ec6ba, __VMLINUX_SYMBOL_STR(drm_modeset_lock_all_ctx) },
	{ 0x1dd71f7a, __VMLINUX_SYMBOL_STR(drm_err) },
	{ 0xeb75b333, __VMLINUX_SYMBOL_STR(drm_format_info_min_pitch) },
	{ 0xdee8c4a6, __VMLINUX_SYMBOL_STR(drm_property_replace_blob) },
	{ 0x5e73c9de, __VMLINUX_SYMBOL_STR(drm_modeset_unlock) },
	{ 0x1061dd77, __VMLINUX_SYMBOL_STR(drm_modeset_lock) },
	{ 0xf11543ff, __VMLINUX_SYMBOL_STR(find_first_zero_bit) },
	{ 0xcaef1b77, __VMLINUX_SYMBOL_STR(idr_remove) },
	{ 0x1408f891, __VMLINUX_SYMBOL_STR(drm_mode_validate_size) },
	{ 0xc5ab1e79, __VMLINUX_SYMBOL_STR(drm_crtc_wait_one_vblank) },
	{ 0x5591cbf, __VMLINUX_SYMBOL_STR(drm_client_init) },
	{ 0xdcc3a419, __VMLINUX_SYMBOL_STR(copy_user_generic_unrolled) },
	{ 0x6a6b7581, __VMLINUX_SYMBOL_STR(drm_atomic_get_crtc_state) },
	{ 0x98b71c6, __VMLINUX_SYMBOL_STR(fb_dealloc_cmap) },
	{ 0x167c5967, __VMLINUX_SYMBOL_STR(print_hex_dump) },
	{ 0xc3bf75bc, __VMLINUX_SYMBOL_STR(module_put) },
	{ 0x783b3563, __VMLINUX_SYMBOL_STR(wake_up_atomic_t) },
	{ 0x28a636e9, __VMLINUX_SYMBOL_STR(i2c_del_adapter) },
	{ 0xddb37d2a, __VMLINUX_SYMBOL_STR(drm_dev_printk) },
	{ 0xe681d186, __VMLINUX_SYMBOL_STR(drm_framebuffer_remove) },
	{ 0x584e6c9c, __VMLINUX_SYMBOL_STR(drm_mode_set_crtcinfo) },
	{ 0x533a37c2, __VMLINUX_SYMBOL_STR(drm_plane_cleanup) },
	{ 0xb1c3a01a, __VMLINUX_SYMBOL_STR(oops_in_progress) },
	{ 0xedc95699, __VMLINUX_SYMBOL_STR(_dev_info) },
	{ 0x40a9b349, __VMLINUX_SYMBOL_STR(vzalloc) },
	{ 0x78764f4e, __VMLINUX_SYMBOL_STR(pv_irq_ops) },
	{ 0x69248c22, __VMLINUX_SYMBOL_STR(drm_client_dev_hotplug) },
	{ 0xb601be4c, __VMLINUX_SYMBOL_STR(__x86_indirect_thunk_rdx) },
	{ 0x78759f0f, __VMLINUX_SYMBOL_STR(drm_mode_prune_invalid) },
	{ 0x6f36c782, __VMLINUX_SYMBOL_STR(idr_find_slowpath) },
	{ 0x4f94f1ba, __VMLINUX_SYMBOL_STR(idr_get_next) },
	{ 0xfd0160aa, __VMLINUX_SYMBOL_STR(drm_atomic_set_crtc_for_plane) },
	{ 0xa916b694, __VMLINUX_SYMBOL_STR(strnlen) },
	{ 0x7ba5423a, __VMLINUX_SYMBOL_STR(drm_connector_list_iter_end) },
	{ 0x12a38747, __VMLINUX_SYMBOL_STR(usleep_range) },
	{ 0xcb1746e4, __VMLINUX_SYMBOL_STR(sys_fillrect) },
	{ 0x3c1bc0a3, __VMLINUX_SYMBOL_STR(drm_mode_match) },
	{ 0x4c0f1a59, __VMLINUX_SYMBOL_STR(drm_atomic_private_obj_fini) },
	{ 0x40d04664, __VMLINUX_SYMBOL_STR(console_trylock) },
	{ 0xeeec26a7, __VMLINUX_SYMBOL_STR(queue_delayed_work_on) },
	{ 0xf0fdf6cb, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0x3bd1b1f6, __VMLINUX_SYMBOL_STR(msecs_to_jiffies) },
	{ 0xd62c833f, __VMLINUX_SYMBOL_STR(schedule_timeout) },
	{ 0x1000e51, __VMLINUX_SYMBOL_STR(schedule) },
	{ 0x155f4108, __VMLINUX_SYMBOL_STR(___ratelimit) },
	{ 0xae6fcc76, __VMLINUX_SYMBOL_STR(sys_imageblit) },
	{ 0xb053adda, __VMLINUX_SYMBOL_STR(drm_rect_rotate) },
	{ 0x2f8b7e95, __VMLINUX_SYMBOL_STR(drm_sysfs_hotplug_event) },
	{ 0x748b1fe9, __VMLINUX_SYMBOL_STR(drm_atomic_normalize_zpos) },
	{ 0x61aaf493, __VMLINUX_SYMBOL_STR(fb_sys_write) },
	{ 0x21f92f6a, __VMLINUX_SYMBOL_STR(drm_mode_debug_printmodeline) },
	{ 0x2ea2c95c, __VMLINUX_SYMBOL_STR(__x86_indirect_thunk_rax) },
	{ 0x263122f8, __VMLINUX_SYMBOL_STR(wait_for_completion_interruptible_timeout) },
	{ 0xab6cb28a, __VMLINUX_SYMBOL_STR(drm_bridge_mode_fixup) },
	{ 0xd5050155, __VMLINUX_SYMBOL_STR(drm_connector_attach_encoder) },
	{ 0x4a758854, __VMLINUX_SYMBOL_STR(drm_crtc_send_vblank_event) },
	{ 0x9d3093b6, __VMLINUX_SYMBOL_STR(drm_gem_object_lookup) },
	{ 0xa17fb880, __VMLINUX_SYMBOL_STR(drm_crtc_vblank_get) },
	{ 0x16f559d5, __VMLINUX_SYMBOL_STR(drm_mode_object_put) },
	{ 0xf6243f18, __VMLINUX_SYMBOL_STR(drm_add_modes_noedid) },
	{ 0x3b9d009a, __VMLINUX_SYMBOL_STR(drm_format_plane_cpp) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
	{ 0x85e0cdca, __VMLINUX_SYMBOL_STR(dma_fence_wait_timeout) },
	{ 0x41ec4c1a, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x9327f5ce, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irqsave) },
	{ 0xb04604e, __VMLINUX_SYMBOL_STR(drm_warn_on_modeset_not_all_locked) },
	{ 0x8b9e7df7, __VMLINUX_SYMBOL_STR(drm_modeset_acquire_init) },
	{ 0xcf21d241, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0x69a002eb, __VMLINUX_SYMBOL_STR(drm_encoder_cleanup) },
	{ 0x6e7ac51d, __VMLINUX_SYMBOL_STR(framebuffer_alloc) },
	{ 0xc1c7de18, __VMLINUX_SYMBOL_STR(fb_deferred_io_cleanup) },
	{ 0xfdda9794, __VMLINUX_SYMBOL_STR(drm_mode_set_config_internal) },
	{ 0xf403bf17, __VMLINUX_SYMBOL_STR(fb_deferred_io_init) },
	{ 0xa338aaf2, __VMLINUX_SYMBOL_STR(drm_connector_list_iter_begin) },
	{ 0x1e047854, __VMLINUX_SYMBOL_STR(warn_slowpath_fmt) },
	{ 0xacc58df4, __VMLINUX_SYMBOL_STR(drm_crtc_cleanup) },
	{ 0xa28078b2, __VMLINUX_SYMBOL_STR(drm_edid_duplicate) },
	{ 0x64165831, __VMLINUX_SYMBOL_STR(drm_driver_legacy_fb_format) },
	{ 0xf169fcc7, __VMLINUX_SYMBOL_STR(__drm_atomic_state_free) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x69acdf38, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0xb3adaf64, __VMLINUX_SYMBOL_STR(drm_mode_object_get) },
	{ 0x5c8b5ce8, __VMLINUX_SYMBOL_STR(prepare_to_wait) },
	{ 0x99fd20aa, __VMLINUX_SYMBOL_STR(drm_rect_clip_scaled) },
	{ 0x4a19cbb7, __VMLINUX_SYMBOL_STR(drm_client_framebuffer_create) },
	{ 0x7efc1130, __VMLINUX_SYMBOL_STR(drm_mode_equal) },
	{ 0xa4aeafe8, __VMLINUX_SYMBOL_STR(drm_client_framebuffer_delete) },
	{ 0x450c190, __VMLINUX_SYMBOL_STR(class_destroy) },
	{ 0xdf78047e, __VMLINUX_SYMBOL_STR(drm_atomic_private_obj_init) },
	{ 0x4d578f4d, __VMLINUX_SYMBOL_STR(drm_modeset_lock_all) },
	{ 0xfa66f77c, __VMLINUX_SYMBOL_STR(finish_wait) },
	{ 0x99dd9e31, __VMLINUX_SYMBOL_STR(drm_crtc_vblank_count) },
	{ 0x2d50570f, __VMLINUX_SYMBOL_STR(drm_rect_calc_hscale) },
	{ 0x2109a78c, __VMLINUX_SYMBOL_STR(drm_dbg) },
	{ 0x324895d4, __VMLINUX_SYMBOL_STR(cfb_copyarea) },
	{ 0x5da6ac0c, __VMLINUX_SYMBOL_STR(drm_atomic_add_affected_connectors) },
	{ 0x911df1c, __VMLINUX_SYMBOL_STR(drm_mode_probed_add) },
	{ 0x2e0d2f7f, __VMLINUX_SYMBOL_STR(queue_work_on) },
	{ 0x28318305, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0xced69203, __VMLINUX_SYMBOL_STR(drm_modeset_unlock_all) },
	{ 0xd4d3acf0, __VMLINUX_SYMBOL_STR(drm_bridge_mode_set) },
	{ 0x8b4bf754, __VMLINUX_SYMBOL_STR(drm_atomic_get_private_obj_state) },
	{ 0x8fff2316, __VMLINUX_SYMBOL_STR(drm_mode_plane_set_obj_prop) },
	{ 0x45500df7, __VMLINUX_SYMBOL_STR(drm_atomic_add_affected_planes) },
	{ 0x418252b9, __VMLINUX_SYMBOL_STR(drm_dev_dbg) },
	{ 0x323a56f9, __VMLINUX_SYMBOL_STR(drm_mode_validate_driver) },
	{ 0x60e2e8f3, __VMLINUX_SYMBOL_STR(drm_framebuffer_init) },
	{ 0x53f6ffbc, __VMLINUX_SYMBOL_STR(wait_for_completion_timeout) },
	{ 0x7e5df8e3, __VMLINUX_SYMBOL_STR(__class_create) },
	{ 0xcbc9557f, __VMLINUX_SYMBOL_STR(unregister_sysrq_key) },
	{ 0x3ac1fef9, __VMLINUX_SYMBOL_STR(drm_mode_legacy_fb_format) },
	{ 0x84c3276a, __VMLINUX_SYMBOL_STR(drm_mode_object_find) },
	{ 0xae03cdb, __VMLINUX_SYMBOL_STR(drm_connector_list_update) },
	{ 0x88db9f48, __VMLINUX_SYMBOL_STR(__check_object_size) },
	{ 0x84c274f9, __VMLINUX_SYMBOL_STR(try_module_get) },
	{ 0x85f5e2aa, __VMLINUX_SYMBOL_STR(krealloc) },
	{ 0x995b7009, __VMLINUX_SYMBOL_STR(drm_mode_vrefresh) },
	{ 0x18c32162, __VMLINUX_SYMBOL_STR(drm_framebuffer_cleanup) },
	{ 0x6253d0ea, __VMLINUX_SYMBOL_STR(unregister_framebuffer) },
	{ 0xbe4aab04, __VMLINUX_SYMBOL_STR(drm_crtc_add_crc_entry) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=drm,fb_sys_fops,syscopyarea,sysfillrect,sysimgblt";


MODULE_INFO(srcversion, "AA524785EBE411E7AA5F093");
MODULE_INFO(rhelversion, "7.7");
#ifdef RETPOLINE
	MODULE_INFO(retpoline, "Y");
#endif
#ifdef CONFIG_MPROFILE_KERNEL
	MODULE_INFO(mprofile, "Y");
#endif
