#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x28950ef1, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0xe56a9336, __VMLINUX_SYMBOL_STR(snd_pcm_format_width) },
	{ 0x2d3385d3, __VMLINUX_SYMBOL_STR(system_wq) },
	{ 0x2008a83a, __VMLINUX_SYMBOL_STR(snd_soc_dapm_kcontrol_widget) },
	{ 0x98ab5c8d, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x7f59e59, __VMLINUX_SYMBOL_STR(pci_write_config_dword) },
	{ 0xd2b09ce5, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0x99acdb8d, __VMLINUX_SYMBOL_STR(skl_put_pvt_id) },
	{ 0x7b9aa283, __VMLINUX_SYMBOL_STR(snd_hdac_stream_start) },
	{ 0x1ed8b599, __VMLINUX_SYMBOL_STR(__x86_indirect_thunk_r8) },
	{ 0x7c65ba7a, __VMLINUX_SYMBOL_STR(skl_ipc_get_large_config) },
	{ 0x619cb7dd, __VMLINUX_SYMBOL_STR(simple_read_from_buffer) },
	{ 0x9f13414d, __VMLINUX_SYMBOL_STR(debugfs_create_dir) },
	{ 0x8c0822ca, __VMLINUX_SYMBOL_STR(snd_hdac_dsp_cleanup) },
	{ 0x784213a6, __VMLINUX_SYMBOL_STR(pv_lock_ops) },
	{ 0x2a7d71f2, __VMLINUX_SYMBOL_STR(snd_pcm_lib_default_mmap) },
	{ 0x4b7dcf38, __VMLINUX_SYMBOL_STR(_raw_qspin_lock) },
	{ 0x754d539c, __VMLINUX_SYMBOL_STR(strlen) },
	{ 0xe2ec18da, __VMLINUX_SYMBOL_STR(snd_hdac_dsp_trigger) },
	{ 0xa32b26e3, __VMLINUX_SYMBOL_STR(snd_hdac_ext_bus_get_link) },
	{ 0xc2f7c1b1, __VMLINUX_SYMBOL_STR(pci_read_config_byte) },
	{ 0x2325094b, __VMLINUX_SYMBOL_STR(snd_soc_tplg_widget_bind_event) },
	{ 0xc483a55a, __VMLINUX_SYMBOL_STR(dev_set_drvdata) },
	{ 0x8d4d1172, __VMLINUX_SYMBOL_STR(snd_hdac_bus_alloc_stream_pages) },
	{ 0xa0d3db3b, __VMLINUX_SYMBOL_STR(__pm_runtime_suspend) },
	{ 0x3a78144a, __VMLINUX_SYMBOL_STR(snd_pcm_period_elapsed) },
	{ 0xa81816c6, __VMLINUX_SYMBOL_STR(snd_hdac_stream_reset) },
	{ 0x7ae5ad74, __VMLINUX_SYMBOL_STR(sme_active) },
	{ 0x59d5a7f7, __VMLINUX_SYMBOL_STR(dma_set_mask) },
	{ 0xbf4aa8ae, __VMLINUX_SYMBOL_STR(snd_hdac_ext_bus_link_put) },
	{ 0xa33cafe8, __VMLINUX_SYMBOL_STR(cnl_sst_init_fw) },
	{ 0x27965961, __VMLINUX_SYMBOL_STR(snd_hdac_stream_sync_trigger) },
	{ 0x1c3e657e, __VMLINUX_SYMBOL_STR(pci_disable_device) },
	{ 0x8e4bc015, __VMLINUX_SYMBOL_STR(snd_hdac_get_stream) },
	{ 0xda9af6c9, __VMLINUX_SYMBOL_STR(snd_pcm_lib_preallocate_free_for_all) },
	{ 0xcf074e2, __VMLINUX_SYMBOL_STR(snd_soc_set_runtime_hwparams) },
	{ 0xba52fefd, __VMLINUX_SYMBOL_STR(snd_hdac_ext_link_set_stream_id) },
	{ 0xbc518109, __VMLINUX_SYMBOL_STR(snd_hdac_ext_link_clear_stream_id) },
	{ 0xee8ce237, __VMLINUX_SYMBOL_STR(skl_clear_module_cnt) },
	{ 0xa1f9a134, __VMLINUX_SYMBOL_STR(__x86_indirect_thunk_rsi) },
	{ 0x88bfa7e, __VMLINUX_SYMBOL_STR(cancel_work_sync) },
	{ 0x448eac3e, __VMLINUX_SYMBOL_STR(kmemdup) },
	{ 0xc9426d6d, __VMLINUX_SYMBOL_STR(pci_write_config_byte) },
	{ 0x7eba65da, __VMLINUX_SYMBOL_STR(snd_hdac_bus_handle_stream_irq) },
	{ 0x8007d8b0, __VMLINUX_SYMBOL_STR(snd_hdac_ext_bus_get_ml_capabilities) },
	{ 0xeae3dfd6, __VMLINUX_SYMBOL_STR(__const_udelay) },
	{ 0xcf73ce21, __VMLINUX_SYMBOL_STR(pci_release_regions) },
	{ 0x522f24f3, __VMLINUX_SYMBOL_STR(snd_hdac_stream_set_params) },
	{ 0x452c5640, __VMLINUX_SYMBOL_STR(snd_hdac_stream_setup) },
	{ 0x797c8fa9, __VMLINUX_SYMBOL_STR(cancel_delayed_work_sync) },
	{ 0x4ed12f73, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x7baababe, __VMLINUX_SYMBOL_STR(__pm_runtime_resume) },
	{ 0x77138b71, __VMLINUX_SYMBOL_STR(skl_ipc_set_large_config) },
	{ 0x6d8753e9, __VMLINUX_SYMBOL_STR(pm_runtime_allow) },
	{ 0x779bedf3, __VMLINUX_SYMBOL_STR(platform_device_register_full) },
	{ 0x358502c6, __VMLINUX_SYMBOL_STR(snd_hdac_bus_parse_capabilities) },
	{ 0xae9bb4d4, __VMLINUX_SYMBOL_STR(debugfs_create_file) },
	{ 0xdacffaef, __VMLINUX_SYMBOL_STR(skl_ipc_delete_pipeline) },
	{ 0xed603dd8, __VMLINUX_SYMBOL_STR(snd_hdac_acomp_exit) },
	{ 0x91715312, __VMLINUX_SYMBOL_STR(sprintf) },
	{ 0x636c619f, __VMLINUX_SYMBOL_STR(debugfs_remove_recursive) },
	{ 0xf4c91ed, __VMLINUX_SYMBOL_STR(ns_to_timespec) },
	{ 0xa22bcf64, __VMLINUX_SYMBOL_STR(snd_pcm_hw_constraint_integer) },
	{ 0xa2665d8c, __VMLINUX_SYMBOL_STR(skl_dsp_get_core) },
	{ 0x7d11c268, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0x343a1a8, __VMLINUX_SYMBOL_STR(__list_add) },
	{ 0x89b36f, __VMLINUX_SYMBOL_STR(snd_soc_acpi_codec_list) },
	{ 0x53b1ff5b, __VMLINUX_SYMBOL_STR(snd_hdac_ext_stream_set_spib) },
	{ 0xce2840e7, __VMLINUX_SYMBOL_STR(irq_set_irq_wake) },
	{ 0xdb13c5d5, __VMLINUX_SYMBOL_STR(snd_hdac_bus_init_cmd_io) },
	{ 0x71de9b3f, __VMLINUX_SYMBOL_STR(_copy_to_user) },
	{ 0xbe4a1520, __VMLINUX_SYMBOL_STR(pci_set_master) },
	{ 0x98ca2b, __VMLINUX_SYMBOL_STR(snd_hdac_display_power) },
	{ 0xdecb3369, __VMLINUX_SYMBOL_STR(snd_pcm_sgbuf_ops_page) },
	{ 0xf829ddde, __VMLINUX_SYMBOL_STR(kbl_sst_dsp_init) },
	{ 0x76212ad1, __VMLINUX_SYMBOL_STR(default_llseek) },
	{ 0x5bbdc39c, __VMLINUX_SYMBOL_STR(pci_restore_state) },
	{ 0x11089ac7, __VMLINUX_SYMBOL_STR(_ctype) },
	{ 0x1d4519c, __VMLINUX_SYMBOL_STR(dev_err) },
	{ 0x8f64aa4, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irqrestore) },
	{ 0x26f0c318, __VMLINUX_SYMBOL_STR(snd_hdac_stream_sync) },
	{ 0xeed7b9fc, __VMLINUX_SYMBOL_STR(snd_hdac_bus_stop_cmd_io) },
	{ 0x3a40b1f4, __VMLINUX_SYMBOL_STR(cnl_sst_dsp_init) },
	{ 0x47cd98ea, __VMLINUX_SYMBOL_STR(snd_soc_tplg_component_load) },
	{ 0x449ad0a7, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0x897fdd42, __VMLINUX_SYMBOL_STR(snd_hdac_ext_link_stream_reset) },
	{ 0x876310, __VMLINUX_SYMBOL_STR(snd_hdac_ext_stream_spbcap_enable) },
	{ 0x7db9025b, __VMLINUX_SYMBOL_STR(platform_device_alloc) },
	{ 0xe7b00dfb, __VMLINUX_SYMBOL_STR(__x86_indirect_thunk_r13) },
	{ 0x94f48576, __VMLINUX_SYMBOL_STR(skl_get_pvt_instance_id_map) },
	{ 0x9166fada, __VMLINUX_SYMBOL_STR(strncpy) },
	{ 0x50d5b739, __VMLINUX_SYMBOL_STR(platform_device_add) },
	{ 0x6a82fb86, __VMLINUX_SYMBOL_STR(snd_soc_acpi_find_machine) },
	{ 0x5a921311, __VMLINUX_SYMBOL_STR(strncmp) },
	{ 0x9e9fdd9d, __VMLINUX_SYMBOL_STR(memunmap) },
	{ 0xd346dc26, __VMLINUX_SYMBOL_STR(snd_hdac_ext_stream_init_all) },
	{ 0x2143f32b, __VMLINUX_SYMBOL_STR(snd_hdac_ext_stream_set_lpib) },
	{ 0x9abdea30, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x521445b, __VMLINUX_SYMBOL_STR(list_del) },
	{ 0x4e6daf04, __VMLINUX_SYMBOL_STR(snd_pcm_lib_free_pages) },
	{ 0xd5bc0ef5, __VMLINUX_SYMBOL_STR(snd_hdac_ext_stream_release) },
	{ 0xe8057af2, __VMLINUX_SYMBOL_STR(snd_hdac_ext_stream_assign) },
	{ 0xc54b2075, __VMLINUX_SYMBOL_STR(skl_dsp_wake) },
	{ 0x9b36baa6, __VMLINUX_SYMBOL_STR(platform_device_unregister) },
	{ 0xbaad46e1, __VMLINUX_SYMBOL_STR(cnl_sst_dsp_cleanup) },
	{ 0xd6b8e852, __VMLINUX_SYMBOL_STR(request_threaded_irq) },
	{ 0x57d13b7c, __VMLINUX_SYMBOL_STR(snd_pcm_lib_ioctl) },
	{ 0x9c6cf0bb, __VMLINUX_SYMBOL_STR(simple_open) },
	{ 0x15784899, __VMLINUX_SYMBOL_STR(devm_kfree) },
	{ 0xa5e75e9a, __VMLINUX_SYMBOL_STR(acpi_evaluate_dsm) },
	{ 0x5c07cb49, __VMLINUX_SYMBOL_STR(snd_hdac_calc_stream_format) },
	{ 0x2dba276a, __VMLINUX_SYMBOL_STR(__iowrite32_copy) },
	{ 0x6728e776, __VMLINUX_SYMBOL_STR(snd_pcm_lib_malloc_pages) },
	{ 0x438ca717, __VMLINUX_SYMBOL_STR(snd_hdac_ext_bus_link_power_down) },
	{ 0x3de72fdb, __VMLINUX_SYMBOL_STR(snd_hdac_ext_stream_set_dpibr) },
	{ 0xe523ad75, __VMLINUX_SYMBOL_STR(synchronize_irq) },
	{ 0x458dc04f, __VMLINUX_SYMBOL_STR(timecounter_read) },
	{ 0x2f7ea7bd, __VMLINUX_SYMBOL_STR(snd_hdac_stream_cleanup) },
	{ 0x167c5967, __VMLINUX_SYMBOL_STR(print_hex_dump) },
	{ 0xa388671d, __VMLINUX_SYMBOL_STR(snd_hdac_stream_stop) },
	{ 0x26da1e13, __VMLINUX_SYMBOL_STR(snd_hdac_bus_init_chip) },
	{ 0xedc95699, __VMLINUX_SYMBOL_STR(_dev_info) },
	{ 0xdfa082fb, __VMLINUX_SYMBOL_STR(snd_hdac_i915_init) },
	{ 0xb601be4c, __VMLINUX_SYMBOL_STR(__x86_indirect_thunk_rdx) },
	{ 0x30585d56, __VMLINUX_SYMBOL_STR(snd_hdac_stream_free_all) },
	{ 0xa7c8c082, __VMLINUX_SYMBOL_STR(skl_dsp_put_core) },
	{ 0xbff189bd, __VMLINUX_SYMBOL_STR(snd_hdac_ext_stream_drsm_enable) },
	{ 0xfe916dc6, __VMLINUX_SYMBOL_STR(hex_dump_to_buffer) },
	{ 0xbfb28813, __VMLINUX_SYMBOL_STR(snd_hdac_ext_stream_decouple) },
	{ 0x33968c11, __VMLINUX_SYMBOL_STR(sysfs_remove_file_ns) },
	{ 0xf0fdf6cb, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0x9610eab4, __VMLINUX_SYMBOL_STR(pci_intx) },
	{ 0x2e9c6c7, __VMLINUX_SYMBOL_STR(snd_hdac_ext_bus_exit) },
	{ 0x54e5c1c4, __VMLINUX_SYMBOL_STR(snd_hdac_ext_bus_link_power_up_all) },
	{ 0x5a432815, __VMLINUX_SYMBOL_STR(snd_hdac_dsp_prepare) },
	{ 0x8e332829, __VMLINUX_SYMBOL_STR(flush_delayed_work) },
	{ 0xd7439eb7, __VMLINUX_SYMBOL_STR(snd_hdac_bus_free_stream_pages) },
	{ 0x7ed89fbf, __VMLINUX_SYMBOL_STR(devm_snd_soc_register_component) },
	{ 0x2ea2c95c, __VMLINUX_SYMBOL_STR(__x86_indirect_thunk_rax) },
	{ 0xebfdcb96, __VMLINUX_SYMBOL_STR(pci_read_config_dword) },
	{ 0x211f68f1, __VMLINUX_SYMBOL_STR(getnstimeofday64) },
	{ 0xf2c52d16, __VMLINUX_SYMBOL_STR(snd_hdac_ext_stop_streams) },
	{ 0x91f26fac, __VMLINUX_SYMBOL_STR(snd_hdac_ext_link_stream_start) },
	{ 0xced5e959, __VMLINUX_SYMBOL_STR(snd_hdac_stream_timecounter_init) },
	{ 0xc486fa14, __VMLINUX_SYMBOL_STR(bxt_sst_init_fw) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
	{ 0xeb15844b, __VMLINUX_SYMBOL_STR(skl_dsp_sleep) },
	{ 0x49adf7bd, __VMLINUX_SYMBOL_STR(skl_sst_dsp_cleanup) },
	{ 0x2cb61da5, __VMLINUX_SYMBOL_STR(pci_unregister_driver) },
	{ 0xcba925d4, __VMLINUX_SYMBOL_STR(snd_pcm_set_sync) },
	{ 0xaf39f6c0, __VMLINUX_SYMBOL_STR(snd_hdac_ext_bus_ppcap_int_enable) },
	{ 0x123f82f3, __VMLINUX_SYMBOL_STR(getrawmonotonic64) },
	{ 0x7f3ac2dd, __VMLINUX_SYMBOL_STR(snd_hdac_ext_bus_device_remove) },
	{ 0x41ec4c1a, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x2b0b1f28, __VMLINUX_SYMBOL_STR(pci_ioremap_bar) },
	{ 0xe9020809, __VMLINUX_SYMBOL_STR(__dynamic_dev_dbg) },
	{ 0x9327f5ce, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irqsave) },
	{ 0x8904834d, __VMLINUX_SYMBOL_STR(skl_ipc_set_pipeline_state) },
	{ 0xe0d99065, __VMLINUX_SYMBOL_STR(snd_hdac_ext_bus_device_init) },
	{ 0x16c20336, __VMLINUX_SYMBOL_STR(skl_ipc_create_pipeline) },
	{ 0x33c2bd26, __VMLINUX_SYMBOL_STR(skl_sst_init_fw) },
	{ 0xa6fe44d5, __VMLINUX_SYMBOL_STR(snd_hdac_link_free_all) },
	{ 0x1e047854, __VMLINUX_SYMBOL_STR(warn_slowpath_fmt) },
	{ 0x50b4c0ee, __VMLINUX_SYMBOL_STR(snd_hdac_ext_link_stream_setup) },
	{ 0x551d753f, __VMLINUX_SYMBOL_STR(snd_hdac_ext_bus_init) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x14a8d72a, __VMLINUX_SYMBOL_STR(skl_get_pvt_id) },
	{ 0x69acdf38, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0xe7c693a4, __VMLINUX_SYMBOL_STR(snd_hdac_ext_bus_link_power_up) },
	{ 0xc3fc2f, __VMLINUX_SYMBOL_STR(pci_request_regions) },
	{ 0x84066290, __VMLINUX_SYMBOL_STR(snd_hdac_bus_stop_chip) },
	{ 0x7a7f7d68, __VMLINUX_SYMBOL_STR(dma_supported) },
	{ 0x8c10cd5c, __VMLINUX_SYMBOL_STR(snd_pcm_hw_constraint_minmax) },
	{ 0xedc03953, __VMLINUX_SYMBOL_STR(iounmap) },
	{ 0xca2411e2, __VMLINUX_SYMBOL_STR(snd_hdac_bus_reset_link) },
	{ 0x68c7263, __VMLINUX_SYMBOL_STR(ioremap_cache) },
	{ 0x99487493, __VMLINUX_SYMBOL_STR(__pci_register_driver) },
	{ 0x7e7c273f, __VMLINUX_SYMBOL_STR(request_firmware) },
	{ 0x57e3dc99, __VMLINUX_SYMBOL_STR(snd_hdac_ext_link_stream_clear) },
	{ 0x8a84a7b5, __VMLINUX_SYMBOL_STR(snd_pcm_lib_preallocate_pages_for_all) },
	{ 0x7ded388, __VMLINUX_SYMBOL_STR(snd_hdac_ext_bus_ppcap_enable) },
	{ 0x41f54a0c, __VMLINUX_SYMBOL_STR(dev_warn) },
	{ 0xaa3bd994, __VMLINUX_SYMBOL_STR(skl_ipc_init_instance) },
	{ 0x9e97e36d, __VMLINUX_SYMBOL_STR(device_rh_alloc) },
	{ 0x60ec2062, __VMLINUX_SYMBOL_STR(skl_ipc_bind_unbind) },
	{ 0x99b7d0ed, __VMLINUX_SYMBOL_STR(snd_hdac_bus_update_rirb) },
	{ 0x9fc2b217, __VMLINUX_SYMBOL_STR(snd_soc_dai_set_tdm_slot) },
	{ 0x2e0d2f7f, __VMLINUX_SYMBOL_STR(queue_work_on) },
	{ 0x28318305, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0x986d991c, __VMLINUX_SYMBOL_STR(snd_hdac_bus_get_response) },
	{ 0xba8139ba, __VMLINUX_SYMBOL_STR(snd_hdac_bus_enter_link_reset) },
	{ 0xd56b5f64, __VMLINUX_SYMBOL_STR(ktime_get_ts64) },
	{ 0x86e7a6f4, __VMLINUX_SYMBOL_STR(sysfs_create_file_ns) },
	{ 0xba7cc321, __VMLINUX_SYMBOL_STR(snd_hdac_bus_send_cmd) },
	{ 0x46734db7, __VMLINUX_SYMBOL_STR(pci_enable_device) },
	{ 0x636462f8, __VMLINUX_SYMBOL_STR(devm_kmalloc) },
	{ 0x77e2f33, __VMLINUX_SYMBOL_STR(_copy_from_user) },
	{ 0xd196b16c, __VMLINUX_SYMBOL_STR(bxt_sst_dsp_cleanup) },
	{ 0xcd2babf6, __VMLINUX_SYMBOL_STR(skl_sst_dsp_init) },
	{ 0xe35b4f, __VMLINUX_SYMBOL_STR(bxt_sst_dsp_init) },
	{ 0x7cf5b2b3, __VMLINUX_SYMBOL_STR(dev_get_drvdata) },
	{ 0xe315da4a, __VMLINUX_SYMBOL_STR(release_firmware) },
	{ 0x88db9f48, __VMLINUX_SYMBOL_STR(__check_object_size) },
	{ 0x85f5e2aa, __VMLINUX_SYMBOL_STR(krealloc) },
	{ 0xb6c2f3bc, __VMLINUX_SYMBOL_STR(snd_hdac_ext_bus_link_power_down_all) },
	{ 0xf20dabd8, __VMLINUX_SYMBOL_STR(free_irq) },
	{ 0x53108e44, __VMLINUX_SYMBOL_STR(pci_save_state) },
	{ 0xee23857b, __VMLINUX_SYMBOL_STR(platform_device_put) },
	{ 0x17fbce60, __VMLINUX_SYMBOL_STR(sme_me_mask) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=snd-pcm,snd-soc-core,snd-soc-skl-ipc,snd-hda-core,snd-hda-ext-core,snd-soc-acpi";

MODULE_ALIAS("pci:v00008086d00009D70sv*sd*bc*sc*i*");
MODULE_ALIAS("pci:v00008086d00005A98sv*sd*bc*sc*i*");
MODULE_ALIAS("pci:v00008086d00009D71sv*sd*bc*sc*i*");
MODULE_ALIAS("pci:v00008086d00003198sv*sd*bc*sc*i*");
MODULE_ALIAS("pci:v00008086d00009DC8sv*sd*bc*sc*i*");

MODULE_INFO(srcversion, "879364BCFF0A95307A66CE1");
MODULE_INFO(rhelversion, "7.7");
#ifdef RETPOLINE
	MODULE_INFO(retpoline, "Y");
#endif
#ifdef CONFIG_MPROFILE_KERNEL
	MODULE_INFO(mprofile, "Y");
#endif
