#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x28950ef1, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x1976aa06, __VMLINUX_SYMBOL_STR(param_ops_bool) },
	{ 0x5b2835a8, __VMLINUX_SYMBOL_STR(bus_unregister) },
	{ 0x82477240, __VMLINUX_SYMBOL_STR(ida_destroy) },
	{ 0xd374dfba, __VMLINUX_SYMBOL_STR(device_unregister) },
	{ 0xc3d55f5c, __VMLINUX_SYMBOL_STR(bus_register) },
	{ 0x62440d5, __VMLINUX_SYMBOL_STR(device_register) },
	{ 0xaf5517a9, __VMLINUX_SYMBOL_STR(kmem_cache_create) },
	{ 0x466b85b8, __VMLINUX_SYMBOL_STR(libceph_compatible) },
	{ 0xb0c277ee, __VMLINUX_SYMBOL_STR(blk_put_queue) },
	{ 0xbc28fd2e, __VMLINUX_SYMBOL_STR(add_disk) },
	{ 0x71a50dbc, __VMLINUX_SYMBOL_STR(register_blkdev) },
	{ 0x449e00ff, __VMLINUX_SYMBOL_STR(ceph_parse_options) },
	{ 0xc5be78f8, __VMLINUX_SYMBOL_STR(device_add) },
	{ 0x4ec723a3, __VMLINUX_SYMBOL_STR(ceph_monc_wait_osdmap) },
	{ 0x6d691ec5, __VMLINUX_SYMBOL_STR(ceph_osdc_maybe_request_map) },
	{ 0xf7490fa, __VMLINUX_SYMBOL_STR(dev_set_name) },
	{ 0xaee2ce2a, __VMLINUX_SYMBOL_STR(set_disk_ro) },
	{ 0xb25b6ec8, __VMLINUX_SYMBOL_STR(blk_get_queue) },
	{ 0x156cc590, __VMLINUX_SYMBOL_STR(blk_queue_merge_bvec) },
	{ 0xea1f9d8a, __VMLINUX_SYMBOL_STR(blk_queue_io_opt) },
	{ 0xa98189e5, __VMLINUX_SYMBOL_STR(blk_queue_io_min) },
	{ 0x925e00bb, __VMLINUX_SYMBOL_STR(blk_queue_max_segment_size) },
	{ 0xbe0a2f77, __VMLINUX_SYMBOL_STR(blk_queue_max_segments) },
	{ 0x5ef68d5c, __VMLINUX_SYMBOL_STR(blk_queue_max_hw_sectors) },
	{ 0x91ac8b2f, __VMLINUX_SYMBOL_STR(blk_mq_init_queue) },
	{ 0xac338874, __VMLINUX_SYMBOL_STR(blk_mq_alloc_tag_set) },
	{ 0x28318305, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0x7959fc3f, __VMLINUX_SYMBOL_STR(alloc_disk) },
	{ 0x20c05d48, __VMLINUX_SYMBOL_STR(__module_get) },
	{ 0x43a53735, __VMLINUX_SYMBOL_STR(__alloc_workqueue_key) },
	{ 0x44e6ecc8, __VMLINUX_SYMBOL_STR(ida_simple_get) },
	{ 0x94dffb5b, __VMLINUX_SYMBOL_STR(ceph_pg_poolid_by_name) },
	{ 0x864a2f45, __VMLINUX_SYMBOL_STR(ceph_monc_get_version) },
	{ 0xe405b34f, __VMLINUX_SYMBOL_STR(ceph_destroy_options) },
	{ 0x2ec21fdc, __VMLINUX_SYMBOL_STR(ceph_open_session) },
	{ 0xd03f9466, __VMLINUX_SYMBOL_STR(ceph_create_client) },
	{ 0x7d99ad4, __VMLINUX_SYMBOL_STR(ceph_compare_options) },
	{ 0x448eac3e, __VMLINUX_SYMBOL_STR(kmemdup) },
	{ 0x1ac5d3cb, __VMLINUX_SYMBOL_STR(strcspn) },
	{ 0xc29bf967, __VMLINUX_SYMBOL_STR(strspn) },
	{ 0x84c274f9, __VMLINUX_SYMBOL_STR(try_module_get) },
	{ 0xe2d5255a, __VMLINUX_SYMBOL_STR(strcmp) },
	{ 0xb08a71d0, __VMLINUX_SYMBOL_STR(ceph_pg_pool_name_by_id) },
	{ 0xd390de64, __VMLINUX_SYMBOL_STR(ceph_cls_set_cookie) },
	{ 0xde5a4e55, __VMLINUX_SYMBOL_STR(revalidate_disk) },
	{ 0xa8104b85, __VMLINUX_SYMBOL_STR(ceph_copy_from_page_vector) },
	{ 0x15ffaac2, __VMLINUX_SYMBOL_STR(ceph_osdc_wait_request) },
	{ 0xf13af00c, __VMLINUX_SYMBOL_STR(ceph_oloc_copy) },
	{ 0x2087719e, __VMLINUX_SYMBOL_STR(ceph_oid_copy) },
	{ 0x987955da, __VMLINUX_SYMBOL_STR(ceph_oid_printf) },
	{ 0x754d539c, __VMLINUX_SYMBOL_STR(strlen) },
	{ 0x2bfab66f, __VMLINUX_SYMBOL_STR(blk_set_queue_dying) },
	{ 0x2b39b4b, __VMLINUX_SYMBOL_STR(blk_mq_freeze_queue) },
	{ 0x5c1b0517, __VMLINUX_SYMBOL_STR(device_del) },
	{ 0x65e75cb6, __VMLINUX_SYMBOL_STR(__list_del_entry) },
	{ 0x95f82b97, __VMLINUX_SYMBOL_STR(del_gendisk) },
	{ 0x5571ca76, __VMLINUX_SYMBOL_STR(osd_req_op_cls_request_data_pages) },
	{ 0xf63b444d, __VMLINUX_SYMBOL_STR(osd_req_op_cls_init) },
	{ 0x6b2e3bcd, __VMLINUX_SYMBOL_STR(ceph_get_snap_context) },
	{ 0xc476f46, __VMLINUX_SYMBOL_STR(blk_mq_start_request) },
	{ 0x9c97ff25, __VMLINUX_SYMBOL_STR(blk_mq_end_request) },
	{ 0x2e42f03c, __VMLINUX_SYMBOL_STR(osd_req_op_raw_data_in_pages) },
	{ 0x67674356, __VMLINUX_SYMBOL_STR(ceph_alloc_page_vector) },
	{ 0xf9f19243, __VMLINUX_SYMBOL_STR(__blk_mq_end_request) },
	{ 0xf47f5446, __VMLINUX_SYMBOL_STR(blk_update_request) },
	{ 0xd0a0906f, __VMLINUX_SYMBOL_STR(get_device) },
	{ 0x3588d8ba, __VMLINUX_SYMBOL_STR(_raw_qspin_lock_irq) },
	{ 0xc3bf75bc, __VMLINUX_SYMBOL_STR(module_put) },
	{ 0xa9d8f55e, __VMLINUX_SYMBOL_STR(ida_simple_remove) },
	{ 0x8c03d20c, __VMLINUX_SYMBOL_STR(destroy_workqueue) },
	{ 0x17f8bf64, __VMLINUX_SYMBOL_STR(ceph_oloc_destroy) },
	{ 0x7f061699, __VMLINUX_SYMBOL_STR(put_device) },
	{ 0xf23e4ecc, __VMLINUX_SYMBOL_STR(ceph_osdc_start_request) },
	{ 0xad039c54, __VMLINUX_SYMBOL_STR(mod_delayed_work_on) },
	{ 0x3974f05b, __VMLINUX_SYMBOL_STR(ceph_cls_break_lock) },
	{ 0xbe0639dc, __VMLINUX_SYMBOL_STR(ceph_monc_blacklist_add) },
	{ 0xdfc091f9, __VMLINUX_SYMBOL_STR(ceph_entity_type_name) },
	{ 0x449ad0a7, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0x20c55ae0, __VMLINUX_SYMBOL_STR(sscanf) },
	{ 0xc738a748, __VMLINUX_SYMBOL_STR(ceph_osdc_list_watchers) },
	{ 0x97f7d879, __VMLINUX_SYMBOL_STR(ceph_cls_lock) },
	{ 0xbf28ebfa, __VMLINUX_SYMBOL_STR(ceph_free_lockers) },
	{ 0xdcec1581, __VMLINUX_SYMBOL_STR(ceph_cls_lock_info) },
	{ 0x7502c520, __VMLINUX_SYMBOL_STR(bio_clone_bioset) },
	{ 0xeb862489, __VMLINUX_SYMBOL_STR(bio_alloc_bioset) },
	{ 0x30877173, __VMLINUX_SYMBOL_STR(fs_bio_set) },
	{ 0x343a1a8, __VMLINUX_SYMBOL_STR(__list_add) },
	{ 0xc499ae1e, __VMLINUX_SYMBOL_STR(kstrdup) },
	{ 0x2101cbc9, __VMLINUX_SYMBOL_STR(ceph_oid_destroy) },
	{ 0x40677d0d, __VMLINUX_SYMBOL_STR(device_initialize) },
	{ 0xf432dd3d, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0x6b06fdce, __VMLINUX_SYMBOL_STR(delayed_work_timer_fn) },
	{ 0x593a99b, __VMLINUX_SYMBOL_STR(init_timer_key) },
	{ 0x9a025cd5, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0x2a6e6109, __VMLINUX_SYMBOL_STR(__init_rwsem) },
	{ 0x3f688151, __VMLINUX_SYMBOL_STR(ceph_put_snap_context) },
	{ 0xd2b09ce5, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0xae3515ba, __VMLINUX_SYMBOL_STR(ceph_create_snap_context) },
	{ 0xaf6ae696, __VMLINUX_SYMBOL_STR(kstrndup) },
	{ 0x41ec4c1a, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x98ab5c8d, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0xacfa5975, __VMLINUX_SYMBOL_STR(kmem_cache_destroy) },
	{ 0xe6e4137b, __VMLINUX_SYMBOL_STR(ceph_osdc_flush_notifies) },
	{ 0x88bfa7e, __VMLINUX_SYMBOL_STR(cancel_work_sync) },
	{ 0x797c8fa9, __VMLINUX_SYMBOL_STR(cancel_delayed_work_sync) },
	{ 0x1ba377e7, __VMLINUX_SYMBOL_STR(ceph_osdc_unwatch) },
	{ 0xe03f83e7, __VMLINUX_SYMBOL_STR(ceph_osdc_sync) },
	{ 0x73a78bc4, __VMLINUX_SYMBOL_STR(downgrade_write) },
	{ 0xef533390, __VMLINUX_SYMBOL_STR(ceph_osdc_watch) },
	{ 0xcf21d241, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0x5991219c, __VMLINUX_SYMBOL_STR(cancel_delayed_work) },
	{ 0x50a90e8d, __VMLINUX_SYMBOL_STR(bsearch) },
	{ 0xa281370e, __VMLINUX_SYMBOL_STR(__free_pages) },
	{ 0xf0889cb3, __VMLINUX_SYMBOL_STR(ceph_osdc_call) },
	{ 0x69acdf38, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x434693dd, __VMLINUX_SYMBOL_STR(alloc_pages_current) },
	{ 0xb5a459dc, __VMLINUX_SYMBOL_STR(unregister_blkdev) },
	{ 0xd11b7a3e, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0xfa66f77c, __VMLINUX_SYMBOL_STR(finish_wait) },
	{ 0xd62c833f, __VMLINUX_SYMBOL_STR(schedule_timeout) },
	{ 0xf8983de7, __VMLINUX_SYMBOL_STR(prepare_to_wait_exclusive) },
	{ 0xeeec26a7, __VMLINUX_SYMBOL_STR(queue_delayed_work_on) },
	{ 0xc8b57c27, __VMLINUX_SYMBOL_STR(autoremove_wake_function) },
	{ 0x1560360d, __VMLINUX_SYMBOL_STR(ceph_osdc_notify_ack) },
	{ 0x3b4ceb4a, __VMLINUX_SYMBOL_STR(up_write) },
	{ 0xe6e3b875, __VMLINUX_SYMBOL_STR(down_write) },
	{ 0xe5796b, __VMLINUX_SYMBOL_STR(ceph_cls_unlock) },
	{ 0x867c68af, __VMLINUX_SYMBOL_STR(bio_put) },
	{ 0x19ee3d71, __VMLINUX_SYMBOL_STR(kmem_cache_free) },
	{ 0x10517109, __VMLINUX_SYMBOL_STR(ceph_destroy_client) },
	{ 0x784213a6, __VMLINUX_SYMBOL_STR(pv_lock_ops) },
	{ 0x521445b, __VMLINUX_SYMBOL_STR(list_del) },
	{ 0x4b7dcf38, __VMLINUX_SYMBOL_STR(_raw_qspin_lock) },
	{ 0xb74bb3f, __VMLINUX_SYMBOL_STR(osd_req_op_extent_osd_data_pages) },
	{ 0x5580fced, __VMLINUX_SYMBOL_STR(osd_req_op_extent_osd_data_bio) },
	{ 0x1a7031f1, __VMLINUX_SYMBOL_STR(osd_req_op_init) },
	{ 0xf5893abf, __VMLINUX_SYMBOL_STR(up_read) },
	{ 0x57a6ccd0, __VMLINUX_SYMBOL_STR(down_read) },
	{ 0x34184afe, __VMLINUX_SYMBOL_STR(current_kernel_time) },
	{ 0x9ac0ded1, __VMLINUX_SYMBOL_STR(osd_req_op_alloc_hint_init) },
	{ 0x84319134, __VMLINUX_SYMBOL_STR(osd_req_op_extent_init) },
	{ 0xac42d07, __VMLINUX_SYMBOL_STR(ceph_osdc_put_request) },
	{ 0x5ac1c682, __VMLINUX_SYMBOL_STR(ceph_osdc_alloc_messages) },
	{ 0xbf15e03c, __VMLINUX_SYMBOL_STR(ceph_oid_aprintf) },
	{ 0x19bddcf1, __VMLINUX_SYMBOL_STR(ceph_osdc_alloc_request) },
	{ 0x2e6bc2a4, __VMLINUX_SYMBOL_STR(ceph_release_page_vector) },
	{ 0xf30ec4dd, __VMLINUX_SYMBOL_STR(ceph_osdc_notify) },
	{ 0xe914e41e, __VMLINUX_SYMBOL_STR(strcpy) },
	{ 0x3422ea73, __VMLINUX_SYMBOL_STR(ceph_client_addr) },
	{ 0xc8ac9e8, __VMLINUX_SYMBOL_STR(ceph_client_gid) },
	{ 0xf0fdf6cb, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0x4e3567f7, __VMLINUX_SYMBOL_STR(match_int) },
	{ 0x3bd1b1f6, __VMLINUX_SYMBOL_STR(msecs_to_jiffies) },
	{ 0x44e9a829, __VMLINUX_SYMBOL_STR(match_token) },
	{ 0x4ed12f73, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x9abdea30, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0x78764f4e, __VMLINUX_SYMBOL_STR(pv_irq_ops) },
	{ 0xb8c7ff88, __VMLINUX_SYMBOL_STR(current_task) },
	{ 0xfb578fc5, __VMLINUX_SYMBOL_STR(memset) },
	{ 0x7cd8d75e, __VMLINUX_SYMBOL_STR(page_offset_base) },
	{ 0x97651e6c, __VMLINUX_SYMBOL_STR(vmemmap_base) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x58390d3, __VMLINUX_SYMBOL_STR(put_disk) },
	{ 0x5977d514, __VMLINUX_SYMBOL_STR(blk_mq_free_tag_set) },
	{ 0x61762346, __VMLINUX_SYMBOL_STR(blk_cleanup_queue) },
	{ 0x2e0d2f7f, __VMLINUX_SYMBOL_STR(queue_work_on) },
	{ 0x2ea2c95c, __VMLINUX_SYMBOL_STR(__x86_indirect_thunk_rax) },
	{ 0xf087137d, __VMLINUX_SYMBOL_STR(__dynamic_pr_debug) },
	{ 0x6729d3df, __VMLINUX_SYMBOL_STR(__get_user_4) },
	{ 0x91715312, __VMLINUX_SYMBOL_STR(sprintf) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=libceph";


MODULE_INFO(srcversion, "5386BBBD00C262C66CB81F5");
MODULE_INFO(rhelversion, "7.7");
#ifdef RETPOLINE
	MODULE_INFO(retpoline, "Y");
#endif
#ifdef CONFIG_MPROFILE_KERNEL
	MODULE_INFO(mprofile, "Y");
#endif
